// Generated by tools/gen_d3d_trace.py - do not edit.
// Counting hooks on the game's D3D library (SVR2011_D3D_TRACE builds).

#include "d3d_trace.h"

#include <rex/hook.h>
#include <rex/ppc.h>

namespace svr2011::d3d_trace {
const uint32_t kFunctionCount = 562;
const uint32_t kFunctions[] = {
    0x82914828,
    0x829148C8,
    0x82914968,
    0x829149F0,
    0x829149F8,
    0x82914A88,
    0x82914BD8,
    0x82914C30,
    0x82914CF0,
    0x82914D68,
    0x82914DD0,
    0x82914E98,
    0x82914EA8,
    0x82914F58,
    0x82914F68,
    0x829150C0,
    0x82915448,
    0x82915550,
    0x829157B0,
    0x829159D0,
    0x82915D18,
    0x82915D98,
    0x82915DE8,
    0x82915E30,
    0x82915EC8,
    0x82915F68,
    0x82915F80,
    0x82915F98,
    0x82916030,
    0x829160B8,
    0x829161D8,
    0x82916558,
    0x829166B0,
    0x82916A80,
    0x82916B80,
    0x82916C80,
    0x82917168,
    0x82917240,
    0x829172D0,
    0x82917380,
    0x82917678,
    0x829178E8,
    0x829178F8,
    0x829179B0,
    0x829179D0,
    0x82917A88,
    0x82917A90,
    0x82917B40,
    0x82917B48,
    0x82917C68,
    0x82917DA0,
    0x82917E38,
    0x82917E60,
    0x82917EA8,
    0x82917EC8,
    0x82918058,
    0x829180A8,
    0x82918150,
    0x829181B8,
    0x829182D8,
    0x82918750,
    0x82918828,
    0x82918A88,
    0x82919BD8,
    0x82919C28,
    0x82919E08,
    0x82919E38,
    0x82919F00,
    0x82919F18,
    0x82919FF0,
    0x8291A040,
    0x8291A100,
    0x8291A158,
    0x8291A208,
    0x8291A260,
    0x8291A2A0,
    0x8291A2B0,
    0x8291A3C0,
    0x8291A418,
    0x8291A468,
    0x8291A5E0,
    0x8291A6B8,
    0x8291A728,
    0x8291A848,
    0x8291A9F8,
    0x8291AAA0,
    0x8291AC68,
    0x8291ACE8,
    0x8291AEC8,
    0x8291B558,
    0x8291B670,
    0x8291B960,
    0x8291B980,
    0x8291B990,
    0x8291B9B0,
    0x8291B9C0,
    0x8291B9E8,
    0x8291B9F8,
    0x8291BA78,
    0x8291BA88,
    0x8291BB08,
    0x8291BB18,
    0x8291BB98,
    0x8291BBA8,
    0x8291BC28,
    0x8291BC38,
    0x8291BC98,
    0x8291BCA8,
    0x8291BD08,
    0x8291BD18,
    0x8291BD78,
    0x8291BD88,
    0x8291BE10,
    0x8291BE20,
    0x8291BE58,
    0x8291BE80,
    0x8291BEA0,
    0x8291BEB0,
    0x8291BF40,
    0x8291BFB0,
    0x8291BFD8,
    0x8291BFE8,
    0x8291C028,
    0x8291C058,
    0x8291C078,
    0x8291C088,
    0x8291C0C0,
    0x8291C0C8,
    0x8291C0E8,
    0x8291C0F8,
    0x8291C120,
    0x8291C130,
    0x8291C168,
    0x8291C170,
    0x8291C198,
    0x8291C1A8,
    0x8291C1C8,
    0x8291C1D8,
    0x8291C200,
    0x8291C210,
    0x8291C238,
    0x8291C248,
    0x8291C268,
    0x8291C278,
    0x8291C298,
    0x8291C2A8,
    0x8291C2D0,
    0x8291C2E0,
    0x8291C308,
    0x8291C318,
    0x8291C338,
    0x8291C348,
    0x8291C360,
    0x8291C368,
    0x8291C380,
    0x8291C388,
    0x8291C3A0,
    0x8291C3A8,
    0x8291C3C0,
    0x8291C3C8,
    0x8291C3E0,
    0x8291C3E8,
    0x8291C400,
    0x8291C408,
    0x8291C450,
    0x8291C460,
    0x8291C468,
    0x8291C510,
    0x8291C530,
    0x8291C5C8,
    0x8291C5D8,
    0x8291C5F8,
    0x8291C608,
    0x8291C620,
    0x8291C628,
    0x8291C660,
    0x8291C668,
    0x8291C6A0,
    0x8291C6A8,
    0x8291C6E0,
    0x8291C6E8,
    0x8291C720,
    0x8291C728,
    0x8291C730,
    0x8291C738,
    0x8291C780,
    0x8291C790,
    0x8291C7D0,
    0x8291C7E0,
    0x8291C820,
    0x8291C830,
    0x8291C850,
    0x8291C878,
    0x8291C8A0,
    0x8291C8C8,
    0x8291C8F0,
    0x8291C918,
    0x8291C940,
    0x8291C960,
    0x8291C980,
    0x8291C9A8,
    0x8291C9D0,
    0x8291C9F8,
    0x8291CA20,
    0x8291CA48,
    0x8291CA70,
    0x8291CA90,
    0x8291CAA0,
    0x8291CAB0,
    0x8291CAC0,
    0x8291CAD0,
    0x8291CAE0,
    0x8291CAF0,
    0x8291CB00,
    0x8291CB10,
    0x8291CB20,
    0x8291CB30,
    0x8291CB40,
    0x8291CB50,
    0x8291CB60,
    0x8291CB70,
    0x8291CB80,
    0x8291CB90,
    0x8291CBD0,
    0x8291CBE0,
    0x8291CC70,
    0x8291CC78,
    0x8291CD08,
    0x8291CD10,
    0x8291CDA0,
    0x8291CDA8,
    0x8291CE38,
    0x8291CE40,
    0x8291CE68,
    0x8291CE78,
    0x8291CEA0,
    0x8291CEB0,
    0x8291CED8,
    0x8291CEE8,
    0x8291CF10,
    0x8291CF20,
    0x8291CF40,
    0x8291CF50,
    0x8291CF70,
    0x8291CF78,
    0x8291CF98,
    0x8291CFA8,
    0x8291CFC8,
    0x8291CFD0,
    0x8291CFF8,
    0x8291D000,
    0x8291D028,
    0x8291D030,
    0x8291D050,
    0x8291D058,
    0x8291D080,
    0x8291D088,
    0x8291D0A8,
    0x8291D0B8,
    0x8291D110,
    0x8291D120,
    0x8291D140,
    0x8291D150,
    0x8291D170,
    0x8291D180,
    0x8291D1A0,
    0x8291D1B0,
    0x8291D1C8,
    0x8291D1D0,
    0x8291D1D8,
    0x8291D1E0,
    0x8291D1F0,
    0x8291D200,
    0x8291D2C8,
    0x8291D300,
    0x8291D398,
    0x8291D3A8,
    0x8291D470,
    0x8291D4A8,
    0x8291D538,
    0x8291D548,
    0x8291D588,
    0x8291D5A0,
    0x8291D638,
    0x8291D648,
    0x8291D6B0,
    0x8291D6C0,
    0x8291D720,
    0x8291D768,
    0x8291D7C8,
    0x8291D808,
    0x8291D878,
    0x8291D888,
    0x8291D8F8,
    0x8291D908,
    0x8291D950,
    0x8291D978,
    0x8291D9B0,
    0x8291D9C8,
    0x8291DA00,
    0x8291DA18,
    0x8291DA50,
    0x8291DA68,
    0x8291DAA8,
    0x8291DAC0,
    0x8291DB00,
    0x8291DB18,
    0x8291DB58,
    0x8291DB70,
    0x8291DBB0,
    0x8291DBC8,
    0x8291DC10,
    0x8291DC28,
    0x8291DD20,
    0x8291DD70,
    0x8291DE90,
    0x8291DF20,
    0x8291DF68,
    0x8291DFA8,
    0x8291DFE8,
    0x8291E0B8,
    0x8291E188,
    0x8291E280,
    0x8291E4D8,
    0x8291E4E8,
    0x8291E568,
    0x8291E588,
    0x8291E618,
    0x8291E968,
    0x8291EC40,
    0x8291EC48,
    0x8291EF00,
    0x8291F168,
    0x8291F708,
    0x8291FD88,
    0x8291FEB0,
    0x8291FF70,
    0x829204A0,
    0x82920678,
    0x82920790,
    0x829207F0,
    0x82920800,
    0x829208D8,
    0x829209B0,
    0x82920A10,
    0x82920A70,
    0x82920AC8,
    0x82920B20,
    0x82920B58,
    0x82920D18,
    0x82920D60,
    0x82920F30,
    0x82920F78,
    0x82920F90,
    0x82921080,
    0x82921100,
    0x829211E8,
    0x82921230,
    0x82921360,
    0x82921450,
    0x82921548,
    0x82921638,
    0x82921688,
    0x82921698,
    0x82921B58,
    0x82921FD0,
    0x82922068,
    0x82922118,
    0x82922230,
    0x82922298,
    0x829222F0,
    0x82922388,
    0x82922400,
    0x82922630,
    0x82922718,
    0x829227E8,
    0x82922848,
    0x829228A8,
    0x829228F0,
    0x82922A00,
    0x82922AA0,
    0x82922B20,
    0x82922C58,
    0x82923020,
    0x829231E0,
    0x82923320,
    0x829234D0,
    0x82923720,
    0x82923740,
    0x829238C8,
    0x829239D0,
    0x82923A08,
    0x82923A98,
    0x82923B00,
    0x82923B78,
    0x82923BF0,
    0x82923FB8,
    0x82924060,
    0x82924110,
    0x8292416C,
    0x82924170,
    0x82924220,
    0x829242D0,
    0x82924350,
    0x829243C8,
    0x82924420,
    0x829244F8,
    0x82924638,
    0x82924688,
    0x829247F8,
    0x829248B0,
    0x82924AA8,
    0x82924E40,
    0x82924F00,
    0x82925080,
    0x829251D8,
    0x82925328,
    0x82925950,
    0x82925A20,
    0x82925AD8,
    0x82925C28,
    0x82925D78,
    0x82925EC0,
    0x82926000,
    0x82926970,
    0x829269F0,
    0x82926AB8,
    0x82926AC8,
    0x82926AE0,
    0x82926B60,
    0x82926DC8,
    0x82926F10,
    0x82927300,
    0x829273C0,
    0x82927468,
    0x82927488,
    0x829274C8,
    0x829274F0,
    0x82927758,
    0x829279A8,
    0x82927A58,
    0x82927AB0,
    0x82927B58,
    0x82927BF0,
    0x82927C60,
    0x82927EC8,
    0x82927F18,
    0x82927F98,
    0x82928140,
    0x82928190,
    0x82928240,
    0x829282F0,
    0x82928470,
    0x82928508,
    0x82928590,
    0x82928688,
    0x82928778,
    0x829287BC,
    0x829287C0,
    0x82928820,
    0x82928828,
    0x82928998,
    0x82928A00,
    0x82928A58,
    0x82928AE0,
    0x82928B40,
    0x82928C60,
    0x82928C70,
    0x82928CE0,
    0x82928D48,
    0x82928DE8,
    0x82928E80,
    0x82928ED8,
    0x82928F50,
    0x82929028,
    0x829290F0,
    0x82929158,
    0x829291B0,
    0x829291F8,
    0x82929350,
    0x829293F0,
    0x82929500,
    0x82929950,
    0x82929E30,
    0x82929E38,
    0x8292A018,
    0x8292A118,
    0x8292A1D0,
    0x8292A270,
    0x8292AA28,
    0x8292AEC0,
    0x8292B208,
    0x8292B920,
    0x8292BA50,
    0x8292BBC8,
    0x8292BC58,
    0x8292BD30,
    0x8292BFD0,
    0x8292C0F8,
    0x8292C170,
    0x8292C1D0,
    0x8292C270,
    0x8292C358,
    0x8292C540,
    0x8292C998,
    0x8292CB40,
    0x8292CC00,
    0x8292CC58,
    0x8292CD60,
    0x8292CE68,
    0x8292D2A0,
    0x8292D580,
    0x8292DAA8,
    0x8292DC58,
    0x8292DCD8,
    0x8292DD08,
    0x8292DD20,
    0x8292DE08,
    0x8292DE20,
    0x8292DE38,
    0x8292DE70,
    0x8292DEC8,
    0x8292DF10,
    0x8292DF28,
    0x8292DF40,
    0x8292DF68,
    0x8292E220,
    0x8292E2A0,
    0x8292E3A8,
    0x8292EAC8,
    0x8292EB80,
    0x8292EFA0,
    0x8292EFD0,
    0x8292F338,
    0x8292FBF8,
    0x8292FCE8,
    0x8292FD00,
    0x8292FD70,
    0x8292FE58,
    0x8292FEF8,
    0x82930500,
    0x82930518,
    0x82931B88,
    0x82931BF8,
    0x82931CB0,
    0x82931D18,
    0x82931DA0,
    0x82931E40,
    0x82931F48,
    0x82931FB0,
    0x829320E8,
    0x82932120,
    0x829321B8,
    0x82932360,
    0x82932440,
    0x82932580,
    0x82932678,
    0x829329C0,
    0x82932C80,
    0x82932E18,
    0x82932ED0,
    0x82933070,
};
}  // namespace svr2011::d3d_trace

REX_EXTERN(__imp__sub_82914828);
REX_HOOK_RAW(sub_82914828) {
  svr2011::d3d_trace::OnCall(0, ctx, base);
  __imp__sub_82914828(ctx, base);
}
REX_EXTERN(__imp__sub_829148C8);
REX_HOOK_RAW(sub_829148C8) {
  svr2011::d3d_trace::OnCall(1, ctx, base);
  __imp__sub_829148C8(ctx, base);
}
REX_EXTERN(__imp__sub_82914968);
REX_HOOK_RAW(sub_82914968) {
  svr2011::d3d_trace::OnCall(2, ctx, base);
  __imp__sub_82914968(ctx, base);
}
REX_EXTERN(__imp__sub_829149F0);
REX_HOOK_RAW(sub_829149F0) {
  svr2011::d3d_trace::OnCall(3, ctx, base);
  __imp__sub_829149F0(ctx, base);
}
REX_EXTERN(__imp__sub_829149F8);
REX_HOOK_RAW(sub_829149F8) {
  svr2011::d3d_trace::OnCall(4, ctx, base);
  __imp__sub_829149F8(ctx, base);
}
REX_EXTERN(__imp__sub_82914A88);
REX_HOOK_RAW(sub_82914A88) {
  svr2011::d3d_trace::OnCall(5, ctx, base);
  __imp__sub_82914A88(ctx, base);
}
REX_EXTERN(__imp__sub_82914BD8);
REX_HOOK_RAW(sub_82914BD8) {
  svr2011::d3d_trace::OnCall(6, ctx, base);
  __imp__sub_82914BD8(ctx, base);
}
REX_EXTERN(__imp__sub_82914C30);
REX_HOOK_RAW(sub_82914C30) {
  svr2011::d3d_trace::OnCall(7, ctx, base);
  __imp__sub_82914C30(ctx, base);
}
REX_EXTERN(__imp__sub_82914CF0);
REX_HOOK_RAW(sub_82914CF0) {
  svr2011::d3d_trace::OnCall(8, ctx, base);
  __imp__sub_82914CF0(ctx, base);
}
REX_EXTERN(__imp__sub_82914D68);
REX_HOOK_RAW(sub_82914D68) {
  svr2011::d3d_trace::OnCall(9, ctx, base);
  __imp__sub_82914D68(ctx, base);
}
REX_EXTERN(__imp__sub_82914DD0);
REX_HOOK_RAW(sub_82914DD0) {
  svr2011::d3d_trace::OnCall(10, ctx, base);
  __imp__sub_82914DD0(ctx, base);
}
REX_EXTERN(__imp__sub_82914E98);
REX_HOOK_RAW(sub_82914E98) {
  svr2011::d3d_trace::OnCall(11, ctx, base);
  __imp__sub_82914E98(ctx, base);
}
REX_EXTERN(__imp__sub_82914EA8);
REX_HOOK_RAW(sub_82914EA8) {
  svr2011::d3d_trace::OnCall(12, ctx, base);
  __imp__sub_82914EA8(ctx, base);
}
REX_EXTERN(__imp__sub_82914F58);
REX_HOOK_RAW(sub_82914F58) {
  svr2011::d3d_trace::OnCall(13, ctx, base);
  __imp__sub_82914F58(ctx, base);
}
REX_EXTERN(__imp__sub_82914F68);
REX_HOOK_RAW(sub_82914F68) {
  svr2011::d3d_trace::OnCall(14, ctx, base);
  __imp__sub_82914F68(ctx, base);
}
REX_EXTERN(__imp__sub_829150C0);
REX_HOOK_RAW(sub_829150C0) {
  svr2011::d3d_trace::OnCall(15, ctx, base);
  __imp__sub_829150C0(ctx, base);
}
REX_EXTERN(__imp__sub_82915448);
REX_HOOK_RAW(sub_82915448) {
  svr2011::d3d_trace::OnCall(16, ctx, base);
  __imp__sub_82915448(ctx, base);
}
REX_EXTERN(__imp__sub_82915550);
REX_HOOK_RAW(sub_82915550) {
  svr2011::d3d_trace::OnCall(17, ctx, base);
  __imp__sub_82915550(ctx, base);
}
REX_EXTERN(__imp__sub_829157B0);
REX_HOOK_RAW(sub_829157B0) {
  svr2011::d3d_trace::OnCall(18, ctx, base);
  __imp__sub_829157B0(ctx, base);
}
REX_EXTERN(__imp__sub_829159D0);
REX_HOOK_RAW(sub_829159D0) {
  svr2011::d3d_trace::OnCall(19, ctx, base);
  __imp__sub_829159D0(ctx, base);
}
REX_EXTERN(__imp__sub_82915D18);
REX_HOOK_RAW(sub_82915D18) {
  svr2011::d3d_trace::OnCall(20, ctx, base);
  __imp__sub_82915D18(ctx, base);
}
REX_EXTERN(__imp__sub_82915D98);
REX_HOOK_RAW(sub_82915D98) {
  svr2011::d3d_trace::OnCall(21, ctx, base);
  __imp__sub_82915D98(ctx, base);
}
REX_EXTERN(__imp__sub_82915DE8);
REX_HOOK_RAW(sub_82915DE8) {
  svr2011::d3d_trace::OnCall(22, ctx, base);
  __imp__sub_82915DE8(ctx, base);
}
REX_EXTERN(__imp__sub_82915E30);
REX_HOOK_RAW(sub_82915E30) {
  svr2011::d3d_trace::OnCall(23, ctx, base);
  __imp__sub_82915E30(ctx, base);
}
REX_EXTERN(__imp__sub_82915EC8);
REX_HOOK_RAW(sub_82915EC8) {
  svr2011::d3d_trace::OnCall(24, ctx, base);
  __imp__sub_82915EC8(ctx, base);
}
REX_EXTERN(__imp__sub_82915F68);
REX_HOOK_RAW(sub_82915F68) {
  svr2011::d3d_trace::OnCall(25, ctx, base);
  __imp__sub_82915F68(ctx, base);
}
REX_EXTERN(__imp__sub_82915F80);
REX_HOOK_RAW(sub_82915F80) {
  svr2011::d3d_trace::OnCall(26, ctx, base);
  __imp__sub_82915F80(ctx, base);
}
REX_EXTERN(__imp__sub_82915F98);
REX_HOOK_RAW(sub_82915F98) {
  svr2011::d3d_trace::OnCall(27, ctx, base);
  __imp__sub_82915F98(ctx, base);
}
REX_EXTERN(__imp__sub_82916030);
REX_HOOK_RAW(sub_82916030) {
  svr2011::d3d_trace::OnCall(28, ctx, base);
  __imp__sub_82916030(ctx, base);
}
REX_EXTERN(__imp__sub_829160B8);
REX_HOOK_RAW(sub_829160B8) {
  svr2011::d3d_trace::OnCall(29, ctx, base);
  __imp__sub_829160B8(ctx, base);
}
REX_EXTERN(__imp__sub_829161D8);
REX_HOOK_RAW(sub_829161D8) {
  svr2011::d3d_trace::OnCall(30, ctx, base);
  __imp__sub_829161D8(ctx, base);
}
REX_EXTERN(__imp__sub_82916558);
REX_HOOK_RAW(sub_82916558) {
  svr2011::d3d_trace::OnCall(31, ctx, base);
  __imp__sub_82916558(ctx, base);
}
REX_EXTERN(__imp__sub_829166B0);
REX_HOOK_RAW(sub_829166B0) {
  svr2011::d3d_trace::OnCall(32, ctx, base);
  __imp__sub_829166B0(ctx, base);
}
REX_EXTERN(__imp__sub_82916A80);
REX_HOOK_RAW(sub_82916A80) {
  svr2011::d3d_trace::OnCall(33, ctx, base);
  __imp__sub_82916A80(ctx, base);
}
REX_EXTERN(__imp__sub_82916B80);
REX_HOOK_RAW(sub_82916B80) {
  svr2011::d3d_trace::OnCall(34, ctx, base);
  __imp__sub_82916B80(ctx, base);
}
REX_EXTERN(__imp__sub_82916C80);
REX_HOOK_RAW(sub_82916C80) {
  svr2011::d3d_trace::OnCall(35, ctx, base);
  __imp__sub_82916C80(ctx, base);
}
REX_EXTERN(__imp__sub_82917168);
REX_HOOK_RAW(sub_82917168) {
  svr2011::d3d_trace::OnCall(36, ctx, base);
  __imp__sub_82917168(ctx, base);
}
REX_EXTERN(__imp__sub_82917240);
REX_HOOK_RAW(sub_82917240) {
  svr2011::d3d_trace::OnCall(37, ctx, base);
  __imp__sub_82917240(ctx, base);
}
REX_EXTERN(__imp__sub_829172D0);
REX_HOOK_RAW(sub_829172D0) {
  svr2011::d3d_trace::OnCall(38, ctx, base);
  __imp__sub_829172D0(ctx, base);
}
REX_EXTERN(__imp__sub_82917380);
REX_HOOK_RAW(sub_82917380) {
  svr2011::d3d_trace::OnCall(39, ctx, base);
  __imp__sub_82917380(ctx, base);
}
REX_EXTERN(__imp__sub_82917678);
REX_HOOK_RAW(sub_82917678) {
  svr2011::d3d_trace::OnCall(40, ctx, base);
  __imp__sub_82917678(ctx, base);
}
REX_EXTERN(__imp__sub_829178E8);
REX_HOOK_RAW(sub_829178E8) {
  svr2011::d3d_trace::OnCall(41, ctx, base);
  __imp__sub_829178E8(ctx, base);
}
REX_EXTERN(__imp__sub_829178F8);
REX_HOOK_RAW(sub_829178F8) {
  svr2011::d3d_trace::OnCall(42, ctx, base);
  __imp__sub_829178F8(ctx, base);
}
REX_EXTERN(__imp__sub_829179B0);
REX_HOOK_RAW(sub_829179B0) {
  svr2011::d3d_trace::OnCall(43, ctx, base);
  __imp__sub_829179B0(ctx, base);
}
REX_EXTERN(__imp__sub_829179D0);
REX_HOOK_RAW(sub_829179D0) {
  svr2011::d3d_trace::OnCall(44, ctx, base);
  __imp__sub_829179D0(ctx, base);
}
REX_EXTERN(__imp__sub_82917A88);
REX_HOOK_RAW(sub_82917A88) {
  svr2011::d3d_trace::OnCall(45, ctx, base);
  __imp__sub_82917A88(ctx, base);
}
REX_EXTERN(__imp__sub_82917A90);
REX_HOOK_RAW(sub_82917A90) {
  svr2011::d3d_trace::OnCall(46, ctx, base);
  __imp__sub_82917A90(ctx, base);
}
REX_EXTERN(__imp__sub_82917B40);
REX_HOOK_RAW(sub_82917B40) {
  svr2011::d3d_trace::OnCall(47, ctx, base);
  __imp__sub_82917B40(ctx, base);
}
REX_EXTERN(__imp__sub_82917B48);
REX_HOOK_RAW(sub_82917B48) {
  svr2011::d3d_trace::OnCall(48, ctx, base);
  __imp__sub_82917B48(ctx, base);
}
REX_EXTERN(__imp__sub_82917C68);
REX_HOOK_RAW(sub_82917C68) {
  svr2011::d3d_trace::OnCall(49, ctx, base);
  __imp__sub_82917C68(ctx, base);
}
REX_EXTERN(__imp__sub_82917DA0);
REX_HOOK_RAW(sub_82917DA0) {
  svr2011::d3d_trace::OnCall(50, ctx, base);
  __imp__sub_82917DA0(ctx, base);
}
REX_EXTERN(__imp__sub_82917E38);
REX_HOOK_RAW(sub_82917E38) {
  svr2011::d3d_trace::OnCall(51, ctx, base);
  __imp__sub_82917E38(ctx, base);
}
REX_EXTERN(__imp__sub_82917E60);
REX_HOOK_RAW(sub_82917E60) {
  svr2011::d3d_trace::OnCall(52, ctx, base);
  __imp__sub_82917E60(ctx, base);
}
REX_EXTERN(__imp__sub_82917EA8);
REX_HOOK_RAW(sub_82917EA8) {
  svr2011::d3d_trace::OnCall(53, ctx, base);
  __imp__sub_82917EA8(ctx, base);
}
REX_EXTERN(__imp__sub_82917EC8);
REX_HOOK_RAW(sub_82917EC8) {
  svr2011::d3d_trace::OnCall(54, ctx, base);
  __imp__sub_82917EC8(ctx, base);
}
REX_EXTERN(__imp__sub_82918058);
REX_HOOK_RAW(sub_82918058) {
  svr2011::d3d_trace::OnCall(55, ctx, base);
  __imp__sub_82918058(ctx, base);
}
REX_EXTERN(__imp__sub_829180A8);
REX_HOOK_RAW(sub_829180A8) {
  svr2011::d3d_trace::OnCall(56, ctx, base);
  __imp__sub_829180A8(ctx, base);
}
REX_EXTERN(__imp__sub_82918150);
REX_HOOK_RAW(sub_82918150) {
  svr2011::d3d_trace::OnCall(57, ctx, base);
  __imp__sub_82918150(ctx, base);
}
REX_EXTERN(__imp__sub_829181B8);
REX_HOOK_RAW(sub_829181B8) {
  svr2011::d3d_trace::OnCall(58, ctx, base);
  __imp__sub_829181B8(ctx, base);
}
REX_EXTERN(__imp__sub_829182D8);
REX_HOOK_RAW(sub_829182D8) {
  svr2011::d3d_trace::OnCall(59, ctx, base);
  __imp__sub_829182D8(ctx, base);
}
REX_EXTERN(__imp__sub_82918750);
REX_HOOK_RAW(sub_82918750) {
  svr2011::d3d_trace::OnCall(60, ctx, base);
  __imp__sub_82918750(ctx, base);
}
REX_EXTERN(__imp__sub_82918828);
REX_HOOK_RAW(sub_82918828) {
  svr2011::d3d_trace::OnCall(61, ctx, base);
  __imp__sub_82918828(ctx, base);
}
REX_EXTERN(__imp__sub_82918A88);
REX_HOOK_RAW(sub_82918A88) {
  svr2011::d3d_trace::OnCall(62, ctx, base);
  __imp__sub_82918A88(ctx, base);
}
REX_EXTERN(__imp__sub_82919BD8);
REX_HOOK_RAW(sub_82919BD8) {
  svr2011::d3d_trace::OnCall(63, ctx, base);
  __imp__sub_82919BD8(ctx, base);
}
REX_EXTERN(__imp__sub_82919C28);
REX_HOOK_RAW(sub_82919C28) {
  svr2011::d3d_trace::OnCall(64, ctx, base);
  __imp__sub_82919C28(ctx, base);
}
REX_EXTERN(__imp__sub_82919E08);
REX_HOOK_RAW(sub_82919E08) {
  svr2011::d3d_trace::OnCall(65, ctx, base);
  __imp__sub_82919E08(ctx, base);
}
REX_EXTERN(__imp__sub_82919E38);
REX_HOOK_RAW(sub_82919E38) {
  svr2011::d3d_trace::OnCall(66, ctx, base);
  __imp__sub_82919E38(ctx, base);
}
REX_EXTERN(__imp__sub_82919F00);
REX_HOOK_RAW(sub_82919F00) {
  svr2011::d3d_trace::OnCall(67, ctx, base);
  __imp__sub_82919F00(ctx, base);
}
REX_EXTERN(__imp__sub_82919F18);
REX_HOOK_RAW(sub_82919F18) {
  svr2011::d3d_trace::OnCall(68, ctx, base);
  __imp__sub_82919F18(ctx, base);
}
REX_EXTERN(__imp__sub_82919FF0);
REX_HOOK_RAW(sub_82919FF0) {
  svr2011::d3d_trace::OnCall(69, ctx, base);
  __imp__sub_82919FF0(ctx, base);
}
REX_EXTERN(__imp__sub_8291A040);
REX_HOOK_RAW(sub_8291A040) {
  svr2011::d3d_trace::OnCall(70, ctx, base);
  __imp__sub_8291A040(ctx, base);
}
REX_EXTERN(__imp__sub_8291A100);
REX_HOOK_RAW(sub_8291A100) {
  svr2011::d3d_trace::OnCall(71, ctx, base);
  __imp__sub_8291A100(ctx, base);
}
REX_EXTERN(__imp__sub_8291A158);
REX_HOOK_RAW(sub_8291A158) {
  svr2011::d3d_trace::OnCall(72, ctx, base);
  __imp__sub_8291A158(ctx, base);
}
REX_EXTERN(__imp__sub_8291A208);
REX_HOOK_RAW(sub_8291A208) {
  svr2011::d3d_trace::OnCall(73, ctx, base);
  __imp__sub_8291A208(ctx, base);
}
REX_EXTERN(__imp__sub_8291A260);
REX_HOOK_RAW(sub_8291A260) {
  svr2011::d3d_trace::OnCall(74, ctx, base);
  __imp__sub_8291A260(ctx, base);
}
REX_EXTERN(__imp__sub_8291A2A0);
REX_HOOK_RAW(sub_8291A2A0) {
  svr2011::d3d_trace::OnCall(75, ctx, base);
  __imp__sub_8291A2A0(ctx, base);
}
REX_EXTERN(__imp__sub_8291A2B0);
REX_HOOK_RAW(sub_8291A2B0) {
  svr2011::d3d_trace::OnCall(76, ctx, base);
  __imp__sub_8291A2B0(ctx, base);
}
REX_EXTERN(__imp__sub_8291A3C0);
REX_HOOK_RAW(sub_8291A3C0) {
  svr2011::d3d_trace::OnCall(77, ctx, base);
  __imp__sub_8291A3C0(ctx, base);
}
REX_EXTERN(__imp__sub_8291A418);
REX_HOOK_RAW(sub_8291A418) {
  svr2011::d3d_trace::OnCall(78, ctx, base);
  __imp__sub_8291A418(ctx, base);
}
REX_EXTERN(__imp__sub_8291A468);
REX_HOOK_RAW(sub_8291A468) {
  svr2011::d3d_trace::OnCall(79, ctx, base);
  __imp__sub_8291A468(ctx, base);
}
REX_EXTERN(__imp__sub_8291A5E0);
REX_HOOK_RAW(sub_8291A5E0) {
  svr2011::d3d_trace::OnCall(80, ctx, base);
  __imp__sub_8291A5E0(ctx, base);
}
REX_EXTERN(__imp__sub_8291A6B8);
REX_HOOK_RAW(sub_8291A6B8) {
  svr2011::d3d_trace::OnCall(81, ctx, base);
  __imp__sub_8291A6B8(ctx, base);
}
REX_EXTERN(__imp__sub_8291A728);
REX_HOOK_RAW(sub_8291A728) {
  svr2011::d3d_trace::OnCall(82, ctx, base);
  __imp__sub_8291A728(ctx, base);
}
REX_EXTERN(__imp__sub_8291A848);
REX_HOOK_RAW(sub_8291A848) {
  svr2011::d3d_trace::OnCall(83, ctx, base);
  __imp__sub_8291A848(ctx, base);
}
REX_EXTERN(__imp__sub_8291A9F8);
REX_HOOK_RAW(sub_8291A9F8) {
  svr2011::d3d_trace::OnCall(84, ctx, base);
  __imp__sub_8291A9F8(ctx, base);
}
REX_EXTERN(__imp__sub_8291AAA0);
REX_HOOK_RAW(sub_8291AAA0) {
  svr2011::d3d_trace::OnCall(85, ctx, base);
  __imp__sub_8291AAA0(ctx, base);
}
REX_EXTERN(__imp__sub_8291AC68);
REX_HOOK_RAW(sub_8291AC68) {
  svr2011::d3d_trace::OnCall(86, ctx, base);
  __imp__sub_8291AC68(ctx, base);
}
REX_EXTERN(__imp__sub_8291ACE8);
REX_HOOK_RAW(sub_8291ACE8) {
  svr2011::d3d_trace::OnCall(87, ctx, base);
  __imp__sub_8291ACE8(ctx, base);
}
REX_EXTERN(__imp__sub_8291AEC8);
REX_HOOK_RAW(sub_8291AEC8) {
  svr2011::d3d_trace::OnCall(88, ctx, base);
  __imp__sub_8291AEC8(ctx, base);
}
REX_EXTERN(__imp__sub_8291B558);
REX_HOOK_RAW(sub_8291B558) {
  svr2011::d3d_trace::OnCall(89, ctx, base);
  __imp__sub_8291B558(ctx, base);
}
REX_EXTERN(__imp__sub_8291B670);
REX_HOOK_RAW(sub_8291B670) {
  svr2011::d3d_trace::OnCall(90, ctx, base);
  __imp__sub_8291B670(ctx, base);
}
REX_EXTERN(__imp__sub_8291B960);
REX_HOOK_RAW(sub_8291B960) {
  svr2011::d3d_trace::OnCall(91, ctx, base);
  __imp__sub_8291B960(ctx, base);
}
REX_EXTERN(__imp__sub_8291B980);
REX_HOOK_RAW(sub_8291B980) {
  svr2011::d3d_trace::OnCall(92, ctx, base);
  __imp__sub_8291B980(ctx, base);
}
REX_EXTERN(__imp__sub_8291B990);
REX_HOOK_RAW(sub_8291B990) {
  svr2011::d3d_trace::OnCall(93, ctx, base);
  __imp__sub_8291B990(ctx, base);
}
REX_EXTERN(__imp__sub_8291B9B0);
REX_HOOK_RAW(sub_8291B9B0) {
  svr2011::d3d_trace::OnCall(94, ctx, base);
  __imp__sub_8291B9B0(ctx, base);
}
REX_EXTERN(__imp__sub_8291B9C0);
REX_HOOK_RAW(sub_8291B9C0) {
  svr2011::d3d_trace::OnCall(95, ctx, base);
  __imp__sub_8291B9C0(ctx, base);
}
REX_EXTERN(__imp__sub_8291B9E8);
REX_HOOK_RAW(sub_8291B9E8) {
  svr2011::d3d_trace::OnCall(96, ctx, base);
  __imp__sub_8291B9E8(ctx, base);
}
REX_EXTERN(__imp__sub_8291B9F8);
REX_HOOK_RAW(sub_8291B9F8) {
  svr2011::d3d_trace::OnCall(97, ctx, base);
  __imp__sub_8291B9F8(ctx, base);
}
REX_EXTERN(__imp__sub_8291BA78);
REX_HOOK_RAW(sub_8291BA78) {
  svr2011::d3d_trace::OnCall(98, ctx, base);
  __imp__sub_8291BA78(ctx, base);
}
REX_EXTERN(__imp__sub_8291BA88);
REX_HOOK_RAW(sub_8291BA88) {
  svr2011::d3d_trace::OnCall(99, ctx, base);
  __imp__sub_8291BA88(ctx, base);
}
REX_EXTERN(__imp__sub_8291BB08);
REX_HOOK_RAW(sub_8291BB08) {
  svr2011::d3d_trace::OnCall(100, ctx, base);
  __imp__sub_8291BB08(ctx, base);
}
REX_EXTERN(__imp__sub_8291BB18);
REX_HOOK_RAW(sub_8291BB18) {
  svr2011::d3d_trace::OnCall(101, ctx, base);
  __imp__sub_8291BB18(ctx, base);
}
REX_EXTERN(__imp__sub_8291BB98);
REX_HOOK_RAW(sub_8291BB98) {
  svr2011::d3d_trace::OnCall(102, ctx, base);
  __imp__sub_8291BB98(ctx, base);
}
REX_EXTERN(__imp__sub_8291BBA8);
REX_HOOK_RAW(sub_8291BBA8) {
  svr2011::d3d_trace::OnCall(103, ctx, base);
  __imp__sub_8291BBA8(ctx, base);
}
REX_EXTERN(__imp__sub_8291BC28);
REX_HOOK_RAW(sub_8291BC28) {
  svr2011::d3d_trace::OnCall(104, ctx, base);
  __imp__sub_8291BC28(ctx, base);
}
REX_EXTERN(__imp__sub_8291BC38);
REX_HOOK_RAW(sub_8291BC38) {
  svr2011::d3d_trace::OnCall(105, ctx, base);
  __imp__sub_8291BC38(ctx, base);
}
REX_EXTERN(__imp__sub_8291BC98);
REX_HOOK_RAW(sub_8291BC98) {
  svr2011::d3d_trace::OnCall(106, ctx, base);
  __imp__sub_8291BC98(ctx, base);
}
REX_EXTERN(__imp__sub_8291BCA8);
REX_HOOK_RAW(sub_8291BCA8) {
  svr2011::d3d_trace::OnCall(107, ctx, base);
  __imp__sub_8291BCA8(ctx, base);
}
REX_EXTERN(__imp__sub_8291BD08);
REX_HOOK_RAW(sub_8291BD08) {
  svr2011::d3d_trace::OnCall(108, ctx, base);
  __imp__sub_8291BD08(ctx, base);
}
REX_EXTERN(__imp__sub_8291BD18);
REX_HOOK_RAW(sub_8291BD18) {
  svr2011::d3d_trace::OnCall(109, ctx, base);
  __imp__sub_8291BD18(ctx, base);
}
REX_EXTERN(__imp__sub_8291BD78);
REX_HOOK_RAW(sub_8291BD78) {
  svr2011::d3d_trace::OnCall(110, ctx, base);
  __imp__sub_8291BD78(ctx, base);
}
REX_EXTERN(__imp__sub_8291BD88);
REX_HOOK_RAW(sub_8291BD88) {
  svr2011::d3d_trace::OnCall(111, ctx, base);
  __imp__sub_8291BD88(ctx, base);
}
REX_EXTERN(__imp__sub_8291BE10);
REX_HOOK_RAW(sub_8291BE10) {
  svr2011::d3d_trace::OnCall(112, ctx, base);
  __imp__sub_8291BE10(ctx, base);
}
REX_EXTERN(__imp__sub_8291BE20);
REX_HOOK_RAW(sub_8291BE20) {
  svr2011::d3d_trace::OnCall(113, ctx, base);
  __imp__sub_8291BE20(ctx, base);
}
REX_EXTERN(__imp__sub_8291BE58);
REX_HOOK_RAW(sub_8291BE58) {
  svr2011::d3d_trace::OnCall(114, ctx, base);
  __imp__sub_8291BE58(ctx, base);
}
REX_EXTERN(__imp__sub_8291BE80);
REX_HOOK_RAW(sub_8291BE80) {
  svr2011::d3d_trace::OnCall(115, ctx, base);
  __imp__sub_8291BE80(ctx, base);
}
REX_EXTERN(__imp__sub_8291BEA0);
REX_HOOK_RAW(sub_8291BEA0) {
  svr2011::d3d_trace::OnCall(116, ctx, base);
  __imp__sub_8291BEA0(ctx, base);
}
REX_EXTERN(__imp__sub_8291BEB0);
REX_HOOK_RAW(sub_8291BEB0) {
  svr2011::d3d_trace::OnCall(117, ctx, base);
  __imp__sub_8291BEB0(ctx, base);
}
REX_EXTERN(__imp__sub_8291BF40);
REX_HOOK_RAW(sub_8291BF40) {
  svr2011::d3d_trace::OnCall(118, ctx, base);
  __imp__sub_8291BF40(ctx, base);
}
REX_EXTERN(__imp__sub_8291BFB0);
REX_HOOK_RAW(sub_8291BFB0) {
  svr2011::d3d_trace::OnCall(119, ctx, base);
  __imp__sub_8291BFB0(ctx, base);
}
REX_EXTERN(__imp__sub_8291BFD8);
REX_HOOK_RAW(sub_8291BFD8) {
  svr2011::d3d_trace::OnCall(120, ctx, base);
  __imp__sub_8291BFD8(ctx, base);
}
REX_EXTERN(__imp__sub_8291BFE8);
REX_HOOK_RAW(sub_8291BFE8) {
  svr2011::d3d_trace::OnCall(121, ctx, base);
  __imp__sub_8291BFE8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C028);
REX_HOOK_RAW(sub_8291C028) {
  svr2011::d3d_trace::OnCall(122, ctx, base);
  __imp__sub_8291C028(ctx, base);
}
REX_EXTERN(__imp__sub_8291C058);
REX_HOOK_RAW(sub_8291C058) {
  svr2011::d3d_trace::OnCall(123, ctx, base);
  __imp__sub_8291C058(ctx, base);
}
REX_EXTERN(__imp__sub_8291C078);
REX_HOOK_RAW(sub_8291C078) {
  svr2011::d3d_trace::OnCall(124, ctx, base);
  __imp__sub_8291C078(ctx, base);
}
REX_EXTERN(__imp__sub_8291C088);
REX_HOOK_RAW(sub_8291C088) {
  svr2011::d3d_trace::OnCall(125, ctx, base);
  __imp__sub_8291C088(ctx, base);
}
REX_EXTERN(__imp__sub_8291C0C0);
REX_HOOK_RAW(sub_8291C0C0) {
  svr2011::d3d_trace::OnCall(126, ctx, base);
  __imp__sub_8291C0C0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C0C8);
REX_HOOK_RAW(sub_8291C0C8) {
  svr2011::d3d_trace::OnCall(127, ctx, base);
  __imp__sub_8291C0C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C0E8);
REX_HOOK_RAW(sub_8291C0E8) {
  svr2011::d3d_trace::OnCall(128, ctx, base);
  __imp__sub_8291C0E8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C0F8);
REX_HOOK_RAW(sub_8291C0F8) {
  svr2011::d3d_trace::OnCall(129, ctx, base);
  __imp__sub_8291C0F8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C120);
REX_HOOK_RAW(sub_8291C120) {
  svr2011::d3d_trace::OnCall(130, ctx, base);
  __imp__sub_8291C120(ctx, base);
}
REX_EXTERN(__imp__sub_8291C130);
REX_HOOK_RAW(sub_8291C130) {
  svr2011::d3d_trace::OnCall(131, ctx, base);
  __imp__sub_8291C130(ctx, base);
}
REX_EXTERN(__imp__sub_8291C168);
REX_HOOK_RAW(sub_8291C168) {
  svr2011::d3d_trace::OnCall(132, ctx, base);
  __imp__sub_8291C168(ctx, base);
}
REX_EXTERN(__imp__sub_8291C170);
REX_HOOK_RAW(sub_8291C170) {
  svr2011::d3d_trace::OnCall(133, ctx, base);
  __imp__sub_8291C170(ctx, base);
}
REX_EXTERN(__imp__sub_8291C198);
REX_HOOK_RAW(sub_8291C198) {
  svr2011::d3d_trace::OnCall(134, ctx, base);
  __imp__sub_8291C198(ctx, base);
}
REX_EXTERN(__imp__sub_8291C1A8);
REX_HOOK_RAW(sub_8291C1A8) {
  svr2011::d3d_trace::OnCall(135, ctx, base);
  __imp__sub_8291C1A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C1C8);
REX_HOOK_RAW(sub_8291C1C8) {
  svr2011::d3d_trace::OnCall(136, ctx, base);
  __imp__sub_8291C1C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C1D8);
REX_HOOK_RAW(sub_8291C1D8) {
  svr2011::d3d_trace::OnCall(137, ctx, base);
  __imp__sub_8291C1D8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C200);
REX_HOOK_RAW(sub_8291C200) {
  svr2011::d3d_trace::OnCall(138, ctx, base);
  __imp__sub_8291C200(ctx, base);
}
REX_EXTERN(__imp__sub_8291C210);
REX_HOOK_RAW(sub_8291C210) {
  svr2011::d3d_trace::OnCall(139, ctx, base);
  __imp__sub_8291C210(ctx, base);
}
REX_EXTERN(__imp__sub_8291C238);
REX_HOOK_RAW(sub_8291C238) {
  svr2011::d3d_trace::OnCall(140, ctx, base);
  __imp__sub_8291C238(ctx, base);
}
REX_EXTERN(__imp__sub_8291C248);
REX_HOOK_RAW(sub_8291C248) {
  svr2011::d3d_trace::OnCall(141, ctx, base);
  __imp__sub_8291C248(ctx, base);
}
REX_EXTERN(__imp__sub_8291C268);
REX_HOOK_RAW(sub_8291C268) {
  svr2011::d3d_trace::OnCall(142, ctx, base);
  __imp__sub_8291C268(ctx, base);
}
REX_EXTERN(__imp__sub_8291C278);
REX_HOOK_RAW(sub_8291C278) {
  svr2011::d3d_trace::OnCall(143, ctx, base);
  __imp__sub_8291C278(ctx, base);
}
REX_EXTERN(__imp__sub_8291C298);
REX_HOOK_RAW(sub_8291C298) {
  svr2011::d3d_trace::OnCall(144, ctx, base);
  __imp__sub_8291C298(ctx, base);
}
REX_EXTERN(__imp__sub_8291C2A8);
REX_HOOK_RAW(sub_8291C2A8) {
  svr2011::d3d_trace::OnCall(145, ctx, base);
  __imp__sub_8291C2A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C2D0);
REX_HOOK_RAW(sub_8291C2D0) {
  svr2011::d3d_trace::OnCall(146, ctx, base);
  __imp__sub_8291C2D0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C2E0);
REX_HOOK_RAW(sub_8291C2E0) {
  svr2011::d3d_trace::OnCall(147, ctx, base);
  __imp__sub_8291C2E0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C308);
REX_HOOK_RAW(sub_8291C308) {
  svr2011::d3d_trace::OnCall(148, ctx, base);
  __imp__sub_8291C308(ctx, base);
}
REX_EXTERN(__imp__sub_8291C318);
REX_HOOK_RAW(sub_8291C318) {
  svr2011::d3d_trace::OnCall(149, ctx, base);
  __imp__sub_8291C318(ctx, base);
}
REX_EXTERN(__imp__sub_8291C338);
REX_HOOK_RAW(sub_8291C338) {
  svr2011::d3d_trace::OnCall(150, ctx, base);
  __imp__sub_8291C338(ctx, base);
}
REX_EXTERN(__imp__sub_8291C348);
REX_HOOK_RAW(sub_8291C348) {
  svr2011::d3d_trace::OnCall(151, ctx, base);
  __imp__sub_8291C348(ctx, base);
}
REX_EXTERN(__imp__sub_8291C360);
REX_HOOK_RAW(sub_8291C360) {
  svr2011::d3d_trace::OnCall(152, ctx, base);
  __imp__sub_8291C360(ctx, base);
}
REX_EXTERN(__imp__sub_8291C368);
REX_HOOK_RAW(sub_8291C368) {
  svr2011::d3d_trace::OnCall(153, ctx, base);
  __imp__sub_8291C368(ctx, base);
}
REX_EXTERN(__imp__sub_8291C380);
REX_HOOK_RAW(sub_8291C380) {
  svr2011::d3d_trace::OnCall(154, ctx, base);
  __imp__sub_8291C380(ctx, base);
}
REX_EXTERN(__imp__sub_8291C388);
REX_HOOK_RAW(sub_8291C388) {
  svr2011::d3d_trace::OnCall(155, ctx, base);
  __imp__sub_8291C388(ctx, base);
}
REX_EXTERN(__imp__sub_8291C3A0);
REX_HOOK_RAW(sub_8291C3A0) {
  svr2011::d3d_trace::OnCall(156, ctx, base);
  __imp__sub_8291C3A0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C3A8);
REX_HOOK_RAW(sub_8291C3A8) {
  svr2011::d3d_trace::OnCall(157, ctx, base);
  __imp__sub_8291C3A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C3C0);
REX_HOOK_RAW(sub_8291C3C0) {
  svr2011::d3d_trace::OnCall(158, ctx, base);
  __imp__sub_8291C3C0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C3C8);
REX_HOOK_RAW(sub_8291C3C8) {
  svr2011::d3d_trace::OnCall(159, ctx, base);
  __imp__sub_8291C3C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C3E0);
REX_HOOK_RAW(sub_8291C3E0) {
  svr2011::d3d_trace::OnCall(160, ctx, base);
  __imp__sub_8291C3E0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C3E8);
REX_HOOK_RAW(sub_8291C3E8) {
  svr2011::d3d_trace::OnCall(161, ctx, base);
  __imp__sub_8291C3E8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C400);
REX_HOOK_RAW(sub_8291C400) {
  svr2011::d3d_trace::OnCall(162, ctx, base);
  __imp__sub_8291C400(ctx, base);
}
REX_EXTERN(__imp__sub_8291C408);
REX_HOOK_RAW(sub_8291C408) {
  svr2011::d3d_trace::OnCall(163, ctx, base);
  __imp__sub_8291C408(ctx, base);
}
REX_EXTERN(__imp__sub_8291C450);
REX_HOOK_RAW(sub_8291C450) {
  svr2011::d3d_trace::OnCall(164, ctx, base);
  __imp__sub_8291C450(ctx, base);
}
REX_EXTERN(__imp__sub_8291C460);
REX_HOOK_RAW(sub_8291C460) {
  svr2011::d3d_trace::OnCall(165, ctx, base);
  __imp__sub_8291C460(ctx, base);
}
REX_EXTERN(__imp__sub_8291C468);
REX_HOOK_RAW(sub_8291C468) {
  svr2011::d3d_trace::OnCall(166, ctx, base);
  __imp__sub_8291C468(ctx, base);
}
REX_EXTERN(__imp__sub_8291C510);
REX_HOOK_RAW(sub_8291C510) {
  svr2011::d3d_trace::OnCall(167, ctx, base);
  __imp__sub_8291C510(ctx, base);
}
REX_EXTERN(__imp__sub_8291C530);
REX_HOOK_RAW(sub_8291C530) {
  svr2011::d3d_trace::OnCall(168, ctx, base);
  __imp__sub_8291C530(ctx, base);
}
REX_EXTERN(__imp__sub_8291C5C8);
REX_HOOK_RAW(sub_8291C5C8) {
  svr2011::d3d_trace::OnCall(169, ctx, base);
  __imp__sub_8291C5C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C5D8);
REX_HOOK_RAW(sub_8291C5D8) {
  svr2011::d3d_trace::OnCall(170, ctx, base);
  __imp__sub_8291C5D8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C5F8);
REX_HOOK_RAW(sub_8291C5F8) {
  svr2011::d3d_trace::OnCall(171, ctx, base);
  __imp__sub_8291C5F8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C608);
REX_HOOK_RAW(sub_8291C608) {
  svr2011::d3d_trace::OnCall(172, ctx, base);
  __imp__sub_8291C608(ctx, base);
}
REX_EXTERN(__imp__sub_8291C620);
REX_HOOK_RAW(sub_8291C620) {
  svr2011::d3d_trace::OnCall(173, ctx, base);
  __imp__sub_8291C620(ctx, base);
}
REX_EXTERN(__imp__sub_8291C628);
REX_HOOK_RAW(sub_8291C628) {
  svr2011::d3d_trace::OnCall(174, ctx, base);
  __imp__sub_8291C628(ctx, base);
}
REX_EXTERN(__imp__sub_8291C660);
REX_HOOK_RAW(sub_8291C660) {
  svr2011::d3d_trace::OnCall(175, ctx, base);
  __imp__sub_8291C660(ctx, base);
}
REX_EXTERN(__imp__sub_8291C668);
REX_HOOK_RAW(sub_8291C668) {
  svr2011::d3d_trace::OnCall(176, ctx, base);
  __imp__sub_8291C668(ctx, base);
}
REX_EXTERN(__imp__sub_8291C6A0);
REX_HOOK_RAW(sub_8291C6A0) {
  svr2011::d3d_trace::OnCall(177, ctx, base);
  __imp__sub_8291C6A0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C6A8);
REX_HOOK_RAW(sub_8291C6A8) {
  svr2011::d3d_trace::OnCall(178, ctx, base);
  __imp__sub_8291C6A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C6E0);
REX_HOOK_RAW(sub_8291C6E0) {
  svr2011::d3d_trace::OnCall(179, ctx, base);
  __imp__sub_8291C6E0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C6E8);
REX_HOOK_RAW(sub_8291C6E8) {
  svr2011::d3d_trace::OnCall(180, ctx, base);
  __imp__sub_8291C6E8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C720);
REX_HOOK_RAW(sub_8291C720) {
  svr2011::d3d_trace::OnCall(181, ctx, base);
  __imp__sub_8291C720(ctx, base);
}
REX_EXTERN(__imp__sub_8291C728);
REX_HOOK_RAW(sub_8291C728) {
  svr2011::d3d_trace::OnCall(182, ctx, base);
  __imp__sub_8291C728(ctx, base);
}
REX_EXTERN(__imp__sub_8291C730);
REX_HOOK_RAW(sub_8291C730) {
  svr2011::d3d_trace::OnCall(183, ctx, base);
  __imp__sub_8291C730(ctx, base);
}
REX_EXTERN(__imp__sub_8291C738);
REX_HOOK_RAW(sub_8291C738) {
  svr2011::d3d_trace::OnCall(184, ctx, base);
  __imp__sub_8291C738(ctx, base);
}
REX_EXTERN(__imp__sub_8291C780);
REX_HOOK_RAW(sub_8291C780) {
  svr2011::d3d_trace::OnCall(185, ctx, base);
  __imp__sub_8291C780(ctx, base);
}
REX_EXTERN(__imp__sub_8291C790);
REX_HOOK_RAW(sub_8291C790) {
  svr2011::d3d_trace::OnCall(186, ctx, base);
  __imp__sub_8291C790(ctx, base);
}
REX_EXTERN(__imp__sub_8291C7D0);
REX_HOOK_RAW(sub_8291C7D0) {
  svr2011::d3d_trace::OnCall(187, ctx, base);
  __imp__sub_8291C7D0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C7E0);
REX_HOOK_RAW(sub_8291C7E0) {
  svr2011::d3d_trace::OnCall(188, ctx, base);
  __imp__sub_8291C7E0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C820);
REX_HOOK_RAW(sub_8291C820) {
  svr2011::d3d_trace::OnCall(189, ctx, base);
  __imp__sub_8291C820(ctx, base);
}
REX_EXTERN(__imp__sub_8291C830);
REX_HOOK_RAW(sub_8291C830) {
  svr2011::d3d_trace::OnCall(190, ctx, base);
  __imp__sub_8291C830(ctx, base);
}
REX_EXTERN(__imp__sub_8291C850);
REX_HOOK_RAW(sub_8291C850) {
  svr2011::d3d_trace::OnCall(191, ctx, base);
  __imp__sub_8291C850(ctx, base);
}
REX_EXTERN(__imp__sub_8291C878);
REX_HOOK_RAW(sub_8291C878) {
  svr2011::d3d_trace::OnCall(192, ctx, base);
  __imp__sub_8291C878(ctx, base);
}
REX_EXTERN(__imp__sub_8291C8A0);
REX_HOOK_RAW(sub_8291C8A0) {
  svr2011::d3d_trace::OnCall(193, ctx, base);
  __imp__sub_8291C8A0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C8C8);
REX_HOOK_RAW(sub_8291C8C8) {
  svr2011::d3d_trace::OnCall(194, ctx, base);
  __imp__sub_8291C8C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C8F0);
REX_HOOK_RAW(sub_8291C8F0) {
  svr2011::d3d_trace::OnCall(195, ctx, base);
  __imp__sub_8291C8F0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C918);
REX_HOOK_RAW(sub_8291C918) {
  svr2011::d3d_trace::OnCall(196, ctx, base);
  __imp__sub_8291C918(ctx, base);
}
REX_EXTERN(__imp__sub_8291C940);
REX_HOOK_RAW(sub_8291C940) {
  svr2011::d3d_trace::OnCall(197, ctx, base);
  __imp__sub_8291C940(ctx, base);
}
REX_EXTERN(__imp__sub_8291C960);
REX_HOOK_RAW(sub_8291C960) {
  svr2011::d3d_trace::OnCall(198, ctx, base);
  __imp__sub_8291C960(ctx, base);
}
REX_EXTERN(__imp__sub_8291C980);
REX_HOOK_RAW(sub_8291C980) {
  svr2011::d3d_trace::OnCall(199, ctx, base);
  __imp__sub_8291C980(ctx, base);
}
REX_EXTERN(__imp__sub_8291C9A8);
REX_HOOK_RAW(sub_8291C9A8) {
  svr2011::d3d_trace::OnCall(200, ctx, base);
  __imp__sub_8291C9A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291C9D0);
REX_HOOK_RAW(sub_8291C9D0) {
  svr2011::d3d_trace::OnCall(201, ctx, base);
  __imp__sub_8291C9D0(ctx, base);
}
REX_EXTERN(__imp__sub_8291C9F8);
REX_HOOK_RAW(sub_8291C9F8) {
  svr2011::d3d_trace::OnCall(202, ctx, base);
  __imp__sub_8291C9F8(ctx, base);
}
REX_EXTERN(__imp__sub_8291CA20);
REX_HOOK_RAW(sub_8291CA20) {
  svr2011::d3d_trace::OnCall(203, ctx, base);
  __imp__sub_8291CA20(ctx, base);
}
REX_EXTERN(__imp__sub_8291CA48);
REX_HOOK_RAW(sub_8291CA48) {
  svr2011::d3d_trace::OnCall(204, ctx, base);
  __imp__sub_8291CA48(ctx, base);
}
REX_EXTERN(__imp__sub_8291CA70);
REX_HOOK_RAW(sub_8291CA70) {
  svr2011::d3d_trace::OnCall(205, ctx, base);
  __imp__sub_8291CA70(ctx, base);
}
REX_EXTERN(__imp__sub_8291CA90);
REX_HOOK_RAW(sub_8291CA90) {
  svr2011::d3d_trace::OnCall(206, ctx, base);
  __imp__sub_8291CA90(ctx, base);
}
REX_EXTERN(__imp__sub_8291CAA0);
REX_HOOK_RAW(sub_8291CAA0) {
  svr2011::d3d_trace::OnCall(207, ctx, base);
  __imp__sub_8291CAA0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CAB0);
REX_HOOK_RAW(sub_8291CAB0) {
  svr2011::d3d_trace::OnCall(208, ctx, base);
  __imp__sub_8291CAB0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CAC0);
REX_HOOK_RAW(sub_8291CAC0) {
  svr2011::d3d_trace::OnCall(209, ctx, base);
  __imp__sub_8291CAC0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CAD0);
REX_HOOK_RAW(sub_8291CAD0) {
  svr2011::d3d_trace::OnCall(210, ctx, base);
  __imp__sub_8291CAD0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CAE0);
REX_HOOK_RAW(sub_8291CAE0) {
  svr2011::d3d_trace::OnCall(211, ctx, base);
  __imp__sub_8291CAE0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CAF0);
REX_HOOK_RAW(sub_8291CAF0) {
  svr2011::d3d_trace::OnCall(212, ctx, base);
  __imp__sub_8291CAF0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB00);
REX_HOOK_RAW(sub_8291CB00) {
  svr2011::d3d_trace::OnCall(213, ctx, base);
  __imp__sub_8291CB00(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB10);
REX_HOOK_RAW(sub_8291CB10) {
  svr2011::d3d_trace::OnCall(214, ctx, base);
  __imp__sub_8291CB10(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB20);
REX_HOOK_RAW(sub_8291CB20) {
  svr2011::d3d_trace::OnCall(215, ctx, base);
  __imp__sub_8291CB20(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB30);
REX_HOOK_RAW(sub_8291CB30) {
  svr2011::d3d_trace::OnCall(216, ctx, base);
  __imp__sub_8291CB30(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB40);
REX_HOOK_RAW(sub_8291CB40) {
  svr2011::d3d_trace::OnCall(217, ctx, base);
  __imp__sub_8291CB40(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB50);
REX_HOOK_RAW(sub_8291CB50) {
  svr2011::d3d_trace::OnCall(218, ctx, base);
  __imp__sub_8291CB50(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB60);
REX_HOOK_RAW(sub_8291CB60) {
  svr2011::d3d_trace::OnCall(219, ctx, base);
  __imp__sub_8291CB60(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB70);
REX_HOOK_RAW(sub_8291CB70) {
  svr2011::d3d_trace::OnCall(220, ctx, base);
  __imp__sub_8291CB70(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB80);
REX_HOOK_RAW(sub_8291CB80) {
  svr2011::d3d_trace::OnCall(221, ctx, base);
  __imp__sub_8291CB80(ctx, base);
}
REX_EXTERN(__imp__sub_8291CB90);
REX_HOOK_RAW(sub_8291CB90) {
  svr2011::d3d_trace::OnCall(222, ctx, base);
  __imp__sub_8291CB90(ctx, base);
}
REX_EXTERN(__imp__sub_8291CBD0);
REX_HOOK_RAW(sub_8291CBD0) {
  svr2011::d3d_trace::OnCall(223, ctx, base);
  __imp__sub_8291CBD0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CBE0);
REX_HOOK_RAW(sub_8291CBE0) {
  svr2011::d3d_trace::OnCall(224, ctx, base);
  __imp__sub_8291CBE0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CC70);
REX_HOOK_RAW(sub_8291CC70) {
  svr2011::d3d_trace::OnCall(225, ctx, base);
  __imp__sub_8291CC70(ctx, base);
}
REX_EXTERN(__imp__sub_8291CC78);
REX_HOOK_RAW(sub_8291CC78) {
  svr2011::d3d_trace::OnCall(226, ctx, base);
  __imp__sub_8291CC78(ctx, base);
}
REX_EXTERN(__imp__sub_8291CD08);
REX_HOOK_RAW(sub_8291CD08) {
  svr2011::d3d_trace::OnCall(227, ctx, base);
  __imp__sub_8291CD08(ctx, base);
}
REX_EXTERN(__imp__sub_8291CD10);
REX_HOOK_RAW(sub_8291CD10) {
  svr2011::d3d_trace::OnCall(228, ctx, base);
  __imp__sub_8291CD10(ctx, base);
}
REX_EXTERN(__imp__sub_8291CDA0);
REX_HOOK_RAW(sub_8291CDA0) {
  svr2011::d3d_trace::OnCall(229, ctx, base);
  __imp__sub_8291CDA0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CDA8);
REX_HOOK_RAW(sub_8291CDA8) {
  svr2011::d3d_trace::OnCall(230, ctx, base);
  __imp__sub_8291CDA8(ctx, base);
}
REX_EXTERN(__imp__sub_8291CE38);
REX_HOOK_RAW(sub_8291CE38) {
  svr2011::d3d_trace::OnCall(231, ctx, base);
  __imp__sub_8291CE38(ctx, base);
}
REX_EXTERN(__imp__sub_8291CE40);
REX_HOOK_RAW(sub_8291CE40) {
  svr2011::d3d_trace::OnCall(232, ctx, base);
  __imp__sub_8291CE40(ctx, base);
}
REX_EXTERN(__imp__sub_8291CE68);
REX_HOOK_RAW(sub_8291CE68) {
  svr2011::d3d_trace::OnCall(233, ctx, base);
  __imp__sub_8291CE68(ctx, base);
}
REX_EXTERN(__imp__sub_8291CE78);
REX_HOOK_RAW(sub_8291CE78) {
  svr2011::d3d_trace::OnCall(234, ctx, base);
  __imp__sub_8291CE78(ctx, base);
}
REX_EXTERN(__imp__sub_8291CEA0);
REX_HOOK_RAW(sub_8291CEA0) {
  svr2011::d3d_trace::OnCall(235, ctx, base);
  __imp__sub_8291CEA0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CEB0);
REX_HOOK_RAW(sub_8291CEB0) {
  svr2011::d3d_trace::OnCall(236, ctx, base);
  __imp__sub_8291CEB0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CED8);
REX_HOOK_RAW(sub_8291CED8) {
  svr2011::d3d_trace::OnCall(237, ctx, base);
  __imp__sub_8291CED8(ctx, base);
}
REX_EXTERN(__imp__sub_8291CEE8);
REX_HOOK_RAW(sub_8291CEE8) {
  svr2011::d3d_trace::OnCall(238, ctx, base);
  __imp__sub_8291CEE8(ctx, base);
}
REX_EXTERN(__imp__sub_8291CF10);
REX_HOOK_RAW(sub_8291CF10) {
  svr2011::d3d_trace::OnCall(239, ctx, base);
  __imp__sub_8291CF10(ctx, base);
}
REX_EXTERN(__imp__sub_8291CF20);
REX_HOOK_RAW(sub_8291CF20) {
  svr2011::d3d_trace::OnCall(240, ctx, base);
  __imp__sub_8291CF20(ctx, base);
}
REX_EXTERN(__imp__sub_8291CF40);
REX_HOOK_RAW(sub_8291CF40) {
  svr2011::d3d_trace::OnCall(241, ctx, base);
  __imp__sub_8291CF40(ctx, base);
}
REX_EXTERN(__imp__sub_8291CF50);
REX_HOOK_RAW(sub_8291CF50) {
  svr2011::d3d_trace::OnCall(242, ctx, base);
  __imp__sub_8291CF50(ctx, base);
}
REX_EXTERN(__imp__sub_8291CF70);
REX_HOOK_RAW(sub_8291CF70) {
  svr2011::d3d_trace::OnCall(243, ctx, base);
  __imp__sub_8291CF70(ctx, base);
}
REX_EXTERN(__imp__sub_8291CF78);
REX_HOOK_RAW(sub_8291CF78) {
  svr2011::d3d_trace::OnCall(244, ctx, base);
  __imp__sub_8291CF78(ctx, base);
}
REX_EXTERN(__imp__sub_8291CF98);
REX_HOOK_RAW(sub_8291CF98) {
  svr2011::d3d_trace::OnCall(245, ctx, base);
  __imp__sub_8291CF98(ctx, base);
}
REX_EXTERN(__imp__sub_8291CFA8);
REX_HOOK_RAW(sub_8291CFA8) {
  svr2011::d3d_trace::OnCall(246, ctx, base);
  __imp__sub_8291CFA8(ctx, base);
}
REX_EXTERN(__imp__sub_8291CFC8);
REX_HOOK_RAW(sub_8291CFC8) {
  svr2011::d3d_trace::OnCall(247, ctx, base);
  __imp__sub_8291CFC8(ctx, base);
}
REX_EXTERN(__imp__sub_8291CFD0);
REX_HOOK_RAW(sub_8291CFD0) {
  svr2011::d3d_trace::OnCall(248, ctx, base);
  __imp__sub_8291CFD0(ctx, base);
}
REX_EXTERN(__imp__sub_8291CFF8);
REX_HOOK_RAW(sub_8291CFF8) {
  svr2011::d3d_trace::OnCall(249, ctx, base);
  __imp__sub_8291CFF8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D000);
REX_HOOK_RAW(sub_8291D000) {
  svr2011::d3d_trace::OnCall(250, ctx, base);
  __imp__sub_8291D000(ctx, base);
}
REX_EXTERN(__imp__sub_8291D028);
REX_HOOK_RAW(sub_8291D028) {
  svr2011::d3d_trace::OnCall(251, ctx, base);
  __imp__sub_8291D028(ctx, base);
}
REX_EXTERN(__imp__sub_8291D030);
REX_HOOK_RAW(sub_8291D030) {
  svr2011::d3d_trace::OnCall(252, ctx, base);
  __imp__sub_8291D030(ctx, base);
}
REX_EXTERN(__imp__sub_8291D050);
REX_HOOK_RAW(sub_8291D050) {
  svr2011::d3d_trace::OnCall(253, ctx, base);
  __imp__sub_8291D050(ctx, base);
}
REX_EXTERN(__imp__sub_8291D058);
REX_HOOK_RAW(sub_8291D058) {
  svr2011::d3d_trace::OnCall(254, ctx, base);
  __imp__sub_8291D058(ctx, base);
}
REX_EXTERN(__imp__sub_8291D080);
REX_HOOK_RAW(sub_8291D080) {
  svr2011::d3d_trace::OnCall(255, ctx, base);
  __imp__sub_8291D080(ctx, base);
}
REX_EXTERN(__imp__sub_8291D088);
REX_HOOK_RAW(sub_8291D088) {
  svr2011::d3d_trace::OnCall(256, ctx, base);
  __imp__sub_8291D088(ctx, base);
}
REX_EXTERN(__imp__sub_8291D0A8);
REX_HOOK_RAW(sub_8291D0A8) {
  svr2011::d3d_trace::OnCall(257, ctx, base);
  __imp__sub_8291D0A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D0B8);
REX_HOOK_RAW(sub_8291D0B8) {
  svr2011::d3d_trace::OnCall(258, ctx, base);
  __imp__sub_8291D0B8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D110);
REX_HOOK_RAW(sub_8291D110) {
  svr2011::d3d_trace::OnCall(259, ctx, base);
  __imp__sub_8291D110(ctx, base);
}
REX_EXTERN(__imp__sub_8291D120);
REX_HOOK_RAW(sub_8291D120) {
  svr2011::d3d_trace::OnCall(260, ctx, base);
  __imp__sub_8291D120(ctx, base);
}
REX_EXTERN(__imp__sub_8291D140);
REX_HOOK_RAW(sub_8291D140) {
  svr2011::d3d_trace::OnCall(261, ctx, base);
  __imp__sub_8291D140(ctx, base);
}
REX_EXTERN(__imp__sub_8291D150);
REX_HOOK_RAW(sub_8291D150) {
  svr2011::d3d_trace::OnCall(262, ctx, base);
  __imp__sub_8291D150(ctx, base);
}
REX_EXTERN(__imp__sub_8291D170);
REX_HOOK_RAW(sub_8291D170) {
  svr2011::d3d_trace::OnCall(263, ctx, base);
  __imp__sub_8291D170(ctx, base);
}
REX_EXTERN(__imp__sub_8291D180);
REX_HOOK_RAW(sub_8291D180) {
  svr2011::d3d_trace::OnCall(264, ctx, base);
  __imp__sub_8291D180(ctx, base);
}
REX_EXTERN(__imp__sub_8291D1A0);
REX_HOOK_RAW(sub_8291D1A0) {
  svr2011::d3d_trace::OnCall(265, ctx, base);
  __imp__sub_8291D1A0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D1B0);
REX_HOOK_RAW(sub_8291D1B0) {
  svr2011::d3d_trace::OnCall(266, ctx, base);
  __imp__sub_8291D1B0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D1C8);
REX_HOOK_RAW(sub_8291D1C8) {
  svr2011::d3d_trace::OnCall(267, ctx, base);
  __imp__sub_8291D1C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D1D0);
REX_HOOK_RAW(sub_8291D1D0) {
  svr2011::d3d_trace::OnCall(268, ctx, base);
  __imp__sub_8291D1D0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D1D8);
REX_HOOK_RAW(sub_8291D1D8) {
  svr2011::d3d_trace::OnCall(269, ctx, base);
  __imp__sub_8291D1D8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D1E0);
REX_HOOK_RAW(sub_8291D1E0) {
  svr2011::d3d_trace::OnCall(270, ctx, base);
  __imp__sub_8291D1E0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D1F0);
REX_HOOK_RAW(sub_8291D1F0) {
  svr2011::d3d_trace::OnCall(271, ctx, base);
  __imp__sub_8291D1F0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D200);
REX_HOOK_RAW(sub_8291D200) {
  svr2011::d3d_trace::OnCall(272, ctx, base);
  __imp__sub_8291D200(ctx, base);
}
REX_EXTERN(__imp__sub_8291D2C8);
REX_HOOK_RAW(sub_8291D2C8) {
  svr2011::d3d_trace::OnCall(273, ctx, base);
  __imp__sub_8291D2C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D300);
REX_HOOK_RAW(sub_8291D300) {
  svr2011::d3d_trace::OnCall(274, ctx, base);
  __imp__sub_8291D300(ctx, base);
}
REX_EXTERN(__imp__sub_8291D398);
REX_HOOK_RAW(sub_8291D398) {
  svr2011::d3d_trace::OnCall(275, ctx, base);
  __imp__sub_8291D398(ctx, base);
}
REX_EXTERN(__imp__sub_8291D3A8);
REX_HOOK_RAW(sub_8291D3A8) {
  svr2011::d3d_trace::OnCall(276, ctx, base);
  __imp__sub_8291D3A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D470);
REX_HOOK_RAW(sub_8291D470) {
  svr2011::d3d_trace::OnCall(277, ctx, base);
  __imp__sub_8291D470(ctx, base);
}
REX_EXTERN(__imp__sub_8291D4A8);
REX_HOOK_RAW(sub_8291D4A8) {
  svr2011::d3d_trace::OnCall(278, ctx, base);
  __imp__sub_8291D4A8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D538);
REX_HOOK_RAW(sub_8291D538) {
  svr2011::d3d_trace::OnCall(279, ctx, base);
  __imp__sub_8291D538(ctx, base);
}
REX_EXTERN(__imp__sub_8291D548);
REX_HOOK_RAW(sub_8291D548) {
  svr2011::d3d_trace::OnCall(280, ctx, base);
  __imp__sub_8291D548(ctx, base);
}
REX_EXTERN(__imp__sub_8291D588);
REX_HOOK_RAW(sub_8291D588) {
  svr2011::d3d_trace::OnCall(281, ctx, base);
  __imp__sub_8291D588(ctx, base);
}
REX_EXTERN(__imp__sub_8291D5A0);
REX_HOOK_RAW(sub_8291D5A0) {
  svr2011::d3d_trace::OnCall(282, ctx, base);
  __imp__sub_8291D5A0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D638);
REX_HOOK_RAW(sub_8291D638) {
  svr2011::d3d_trace::OnCall(283, ctx, base);
  __imp__sub_8291D638(ctx, base);
}
REX_EXTERN(__imp__sub_8291D648);
REX_HOOK_RAW(sub_8291D648) {
  svr2011::d3d_trace::OnCall(284, ctx, base);
  __imp__sub_8291D648(ctx, base);
}
REX_EXTERN(__imp__sub_8291D6B0);
REX_HOOK_RAW(sub_8291D6B0) {
  svr2011::d3d_trace::OnCall(285, ctx, base);
  __imp__sub_8291D6B0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D6C0);
REX_HOOK_RAW(sub_8291D6C0) {
  svr2011::d3d_trace::OnCall(286, ctx, base);
  __imp__sub_8291D6C0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D720);
REX_HOOK_RAW(sub_8291D720) {
  svr2011::d3d_trace::OnCall(287, ctx, base);
  __imp__sub_8291D720(ctx, base);
}
REX_EXTERN(__imp__sub_8291D768);
REX_HOOK_RAW(sub_8291D768) {
  svr2011::d3d_trace::OnCall(288, ctx, base);
  __imp__sub_8291D768(ctx, base);
}
REX_EXTERN(__imp__sub_8291D7C8);
REX_HOOK_RAW(sub_8291D7C8) {
  svr2011::d3d_trace::OnCall(289, ctx, base);
  __imp__sub_8291D7C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D808);
REX_HOOK_RAW(sub_8291D808) {
  svr2011::d3d_trace::OnCall(290, ctx, base);
  __imp__sub_8291D808(ctx, base);
}
REX_EXTERN(__imp__sub_8291D878);
REX_HOOK_RAW(sub_8291D878) {
  svr2011::d3d_trace::OnCall(291, ctx, base);
  __imp__sub_8291D878(ctx, base);
}
REX_EXTERN(__imp__sub_8291D888);
REX_HOOK_RAW(sub_8291D888) {
  svr2011::d3d_trace::OnCall(292, ctx, base);
  __imp__sub_8291D888(ctx, base);
}
REX_EXTERN(__imp__sub_8291D8F8);
REX_HOOK_RAW(sub_8291D8F8) {
  svr2011::d3d_trace::OnCall(293, ctx, base);
  __imp__sub_8291D8F8(ctx, base);
}
REX_EXTERN(__imp__sub_8291D908);
REX_HOOK_RAW(sub_8291D908) {
  svr2011::d3d_trace::OnCall(294, ctx, base);
  __imp__sub_8291D908(ctx, base);
}
REX_EXTERN(__imp__sub_8291D950);
REX_HOOK_RAW(sub_8291D950) {
  svr2011::d3d_trace::OnCall(295, ctx, base);
  __imp__sub_8291D950(ctx, base);
}
REX_EXTERN(__imp__sub_8291D978);
REX_HOOK_RAW(sub_8291D978) {
  svr2011::d3d_trace::OnCall(296, ctx, base);
  __imp__sub_8291D978(ctx, base);
}
REX_EXTERN(__imp__sub_8291D9B0);
REX_HOOK_RAW(sub_8291D9B0) {
  svr2011::d3d_trace::OnCall(297, ctx, base);
  __imp__sub_8291D9B0(ctx, base);
}
REX_EXTERN(__imp__sub_8291D9C8);
REX_HOOK_RAW(sub_8291D9C8) {
  svr2011::d3d_trace::OnCall(298, ctx, base);
  __imp__sub_8291D9C8(ctx, base);
}
REX_EXTERN(__imp__sub_8291DA00);
REX_HOOK_RAW(sub_8291DA00) {
  svr2011::d3d_trace::OnCall(299, ctx, base);
  __imp__sub_8291DA00(ctx, base);
}
REX_EXTERN(__imp__sub_8291DA18);
REX_HOOK_RAW(sub_8291DA18) {
  svr2011::d3d_trace::OnCall(300, ctx, base);
  __imp__sub_8291DA18(ctx, base);
}
REX_EXTERN(__imp__sub_8291DA50);
REX_HOOK_RAW(sub_8291DA50) {
  svr2011::d3d_trace::OnCall(301, ctx, base);
  __imp__sub_8291DA50(ctx, base);
}
REX_EXTERN(__imp__sub_8291DA68);
REX_HOOK_RAW(sub_8291DA68) {
  svr2011::d3d_trace::OnCall(302, ctx, base);
  __imp__sub_8291DA68(ctx, base);
}
REX_EXTERN(__imp__sub_8291DAA8);
REX_HOOK_RAW(sub_8291DAA8) {
  svr2011::d3d_trace::OnCall(303, ctx, base);
  __imp__sub_8291DAA8(ctx, base);
}
REX_EXTERN(__imp__sub_8291DAC0);
REX_HOOK_RAW(sub_8291DAC0) {
  svr2011::d3d_trace::OnCall(304, ctx, base);
  __imp__sub_8291DAC0(ctx, base);
}
REX_EXTERN(__imp__sub_8291DB00);
REX_HOOK_RAW(sub_8291DB00) {
  svr2011::d3d_trace::OnCall(305, ctx, base);
  __imp__sub_8291DB00(ctx, base);
}
REX_EXTERN(__imp__sub_8291DB18);
REX_HOOK_RAW(sub_8291DB18) {
  svr2011::d3d_trace::OnCall(306, ctx, base);
  __imp__sub_8291DB18(ctx, base);
}
REX_EXTERN(__imp__sub_8291DB58);
REX_HOOK_RAW(sub_8291DB58) {
  svr2011::d3d_trace::OnCall(307, ctx, base);
  __imp__sub_8291DB58(ctx, base);
}
REX_EXTERN(__imp__sub_8291DB70);
REX_HOOK_RAW(sub_8291DB70) {
  svr2011::d3d_trace::OnCall(308, ctx, base);
  __imp__sub_8291DB70(ctx, base);
}
REX_EXTERN(__imp__sub_8291DBB0);
REX_HOOK_RAW(sub_8291DBB0) {
  svr2011::d3d_trace::OnCall(309, ctx, base);
  __imp__sub_8291DBB0(ctx, base);
}
REX_EXTERN(__imp__sub_8291DBC8);
REX_HOOK_RAW(sub_8291DBC8) {
  svr2011::d3d_trace::OnCall(310, ctx, base);
  __imp__sub_8291DBC8(ctx, base);
}
REX_EXTERN(__imp__sub_8291DC10);
REX_HOOK_RAW(sub_8291DC10) {
  svr2011::d3d_trace::OnCall(311, ctx, base);
  __imp__sub_8291DC10(ctx, base);
}
REX_EXTERN(__imp__sub_8291DC28);
REX_HOOK_RAW(sub_8291DC28) {
  svr2011::d3d_trace::OnCall(312, ctx, base);
  __imp__sub_8291DC28(ctx, base);
}
REX_EXTERN(__imp__sub_8291DD20);
REX_HOOK_RAW(sub_8291DD20) {
  svr2011::d3d_trace::OnCall(313, ctx, base);
  __imp__sub_8291DD20(ctx, base);
}
REX_EXTERN(__imp__sub_8291DD70);
REX_HOOK_RAW(sub_8291DD70) {
  svr2011::d3d_trace::OnCall(314, ctx, base);
  __imp__sub_8291DD70(ctx, base);
}
REX_EXTERN(__imp__sub_8291DE90);
REX_HOOK_RAW(sub_8291DE90) {
  svr2011::d3d_trace::OnCall(315, ctx, base);
  __imp__sub_8291DE90(ctx, base);
}
REX_EXTERN(__imp__sub_8291DF20);
REX_HOOK_RAW(sub_8291DF20) {
  svr2011::d3d_trace::OnCall(316, ctx, base);
  __imp__sub_8291DF20(ctx, base);
}
REX_EXTERN(__imp__sub_8291DF68);
REX_HOOK_RAW(sub_8291DF68) {
  svr2011::d3d_trace::OnCall(317, ctx, base);
  __imp__sub_8291DF68(ctx, base);
}
REX_EXTERN(__imp__sub_8291DFA8);
REX_HOOK_RAW(sub_8291DFA8) {
  svr2011::d3d_trace::OnCall(318, ctx, base);
  __imp__sub_8291DFA8(ctx, base);
}
REX_EXTERN(__imp__sub_8291DFE8);
REX_HOOK_RAW(sub_8291DFE8) {
  svr2011::d3d_trace::OnCall(319, ctx, base);
  __imp__sub_8291DFE8(ctx, base);
}
REX_EXTERN(__imp__sub_8291E0B8);
REX_HOOK_RAW(sub_8291E0B8) {
  svr2011::d3d_trace::OnCall(320, ctx, base);
  __imp__sub_8291E0B8(ctx, base);
}
REX_EXTERN(__imp__sub_8291E188);
REX_HOOK_RAW(sub_8291E188) {
  svr2011::d3d_trace::OnCall(321, ctx, base);
  __imp__sub_8291E188(ctx, base);
}
REX_EXTERN(__imp__sub_8291E280);
REX_HOOK_RAW(sub_8291E280) {
  svr2011::d3d_trace::OnCall(322, ctx, base);
  __imp__sub_8291E280(ctx, base);
}
REX_EXTERN(__imp__sub_8291E4D8);
REX_HOOK_RAW(sub_8291E4D8) {
  svr2011::d3d_trace::OnCall(323, ctx, base);
  __imp__sub_8291E4D8(ctx, base);
}
REX_EXTERN(__imp__sub_8291E4E8);
REX_HOOK_RAW(sub_8291E4E8) {
  svr2011::d3d_trace::OnCall(324, ctx, base);
  __imp__sub_8291E4E8(ctx, base);
}
REX_EXTERN(__imp__sub_8291E568);
REX_HOOK_RAW(sub_8291E568) {
  svr2011::d3d_trace::OnCall(325, ctx, base);
  __imp__sub_8291E568(ctx, base);
}
REX_EXTERN(__imp__sub_8291E588);
REX_HOOK_RAW(sub_8291E588) {
  svr2011::d3d_trace::OnCall(326, ctx, base);
  __imp__sub_8291E588(ctx, base);
}
REX_EXTERN(__imp__sub_8291E618);
REX_HOOK_RAW(sub_8291E618) {
  svr2011::d3d_trace::OnCall(327, ctx, base);
  __imp__sub_8291E618(ctx, base);
}
REX_EXTERN(__imp__sub_8291E968);
REX_HOOK_RAW(sub_8291E968) {
  svr2011::d3d_trace::OnCall(328, ctx, base);
  __imp__sub_8291E968(ctx, base);
}
REX_EXTERN(__imp__sub_8291EC40);
REX_HOOK_RAW(sub_8291EC40) {
  svr2011::d3d_trace::OnCall(329, ctx, base);
  __imp__sub_8291EC40(ctx, base);
}
REX_EXTERN(__imp__sub_8291EC48);
REX_HOOK_RAW(sub_8291EC48) {
  svr2011::d3d_trace::OnCall(330, ctx, base);
  __imp__sub_8291EC48(ctx, base);
}
REX_EXTERN(__imp__sub_8291EF00);
REX_HOOK_RAW(sub_8291EF00) {
  svr2011::d3d_trace::OnCall(331, ctx, base);
  __imp__sub_8291EF00(ctx, base);
}
REX_EXTERN(__imp__sub_8291F168);
REX_HOOK_RAW(sub_8291F168) {
  svr2011::d3d_trace::OnCall(332, ctx, base);
  __imp__sub_8291F168(ctx, base);
}
REX_EXTERN(__imp__sub_8291F708);
REX_HOOK_RAW(sub_8291F708) {
  svr2011::d3d_trace::OnCall(333, ctx, base);
  __imp__sub_8291F708(ctx, base);
}
REX_EXTERN(__imp__sub_8291FD88);
REX_HOOK_RAW(sub_8291FD88) {
  svr2011::d3d_trace::OnCall(334, ctx, base);
  __imp__sub_8291FD88(ctx, base);
}
REX_EXTERN(__imp__sub_8291FEB0);
REX_HOOK_RAW(sub_8291FEB0) {
  svr2011::d3d_trace::OnCall(335, ctx, base);
  __imp__sub_8291FEB0(ctx, base);
}
REX_EXTERN(__imp__sub_8291FF70);
REX_HOOK_RAW(sub_8291FF70) {
  svr2011::d3d_trace::OnCall(336, ctx, base);
  __imp__sub_8291FF70(ctx, base);
}
REX_EXTERN(__imp__sub_829204A0);
REX_HOOK_RAW(sub_829204A0) {
  svr2011::d3d_trace::OnCall(337, ctx, base);
  __imp__sub_829204A0(ctx, base);
}
REX_EXTERN(__imp__sub_82920678);
REX_HOOK_RAW(sub_82920678) {
  svr2011::d3d_trace::OnCall(338, ctx, base);
  __imp__sub_82920678(ctx, base);
}
REX_EXTERN(__imp__sub_82920790);
REX_HOOK_RAW(sub_82920790) {
  svr2011::d3d_trace::OnCall(339, ctx, base);
  __imp__sub_82920790(ctx, base);
}
REX_EXTERN(__imp__sub_829207F0);
REX_HOOK_RAW(sub_829207F0) {
  svr2011::d3d_trace::OnCall(340, ctx, base);
  __imp__sub_829207F0(ctx, base);
}
REX_EXTERN(__imp__sub_82920800);
REX_HOOK_RAW(sub_82920800) {
  svr2011::d3d_trace::OnCall(341, ctx, base);
  __imp__sub_82920800(ctx, base);
}
REX_EXTERN(__imp__sub_829208D8);
REX_HOOK_RAW(sub_829208D8) {
  svr2011::d3d_trace::OnCall(342, ctx, base);
  __imp__sub_829208D8(ctx, base);
}
REX_EXTERN(__imp__sub_829209B0);
REX_HOOK_RAW(sub_829209B0) {
  svr2011::d3d_trace::OnCall(343, ctx, base);
  __imp__sub_829209B0(ctx, base);
}
REX_EXTERN(__imp__sub_82920A10);
REX_HOOK_RAW(sub_82920A10) {
  svr2011::d3d_trace::OnCall(344, ctx, base);
  __imp__sub_82920A10(ctx, base);
}
REX_EXTERN(__imp__sub_82920A70);
REX_HOOK_RAW(sub_82920A70) {
  svr2011::d3d_trace::OnCall(345, ctx, base);
  __imp__sub_82920A70(ctx, base);
}
REX_EXTERN(__imp__sub_82920AC8);
REX_HOOK_RAW(sub_82920AC8) {
  svr2011::d3d_trace::OnCall(346, ctx, base);
  __imp__sub_82920AC8(ctx, base);
}
REX_EXTERN(__imp__sub_82920B20);
REX_HOOK_RAW(sub_82920B20) {
  svr2011::d3d_trace::OnCall(347, ctx, base);
  __imp__sub_82920B20(ctx, base);
}
REX_EXTERN(__imp__sub_82920B58);
REX_HOOK_RAW(sub_82920B58) {
  svr2011::d3d_trace::OnCall(348, ctx, base);
  __imp__sub_82920B58(ctx, base);
}
REX_EXTERN(__imp__sub_82920D18);
REX_HOOK_RAW(sub_82920D18) {
  svr2011::d3d_trace::OnCall(349, ctx, base);
  __imp__sub_82920D18(ctx, base);
}
REX_EXTERN(__imp__sub_82920D60);
REX_HOOK_RAW(sub_82920D60) {
  svr2011::d3d_trace::OnCall(350, ctx, base);
  __imp__sub_82920D60(ctx, base);
}
REX_EXTERN(__imp__sub_82920F30);
REX_HOOK_RAW(sub_82920F30) {
  svr2011::d3d_trace::OnCall(351, ctx, base);
  __imp__sub_82920F30(ctx, base);
}
REX_EXTERN(__imp__sub_82920F78);
REX_HOOK_RAW(sub_82920F78) {
  svr2011::d3d_trace::OnCall(352, ctx, base);
  __imp__sub_82920F78(ctx, base);
}
REX_EXTERN(__imp__sub_82920F90);
REX_HOOK_RAW(sub_82920F90) {
  svr2011::d3d_trace::OnCall(353, ctx, base);
  __imp__sub_82920F90(ctx, base);
}
REX_EXTERN(__imp__sub_82921080);
REX_HOOK_RAW(sub_82921080) {
  svr2011::d3d_trace::OnCall(354, ctx, base);
  __imp__sub_82921080(ctx, base);
}
REX_EXTERN(__imp__sub_82921100);
REX_HOOK_RAW(sub_82921100) {
  svr2011::d3d_trace::OnCall(355, ctx, base);
  __imp__sub_82921100(ctx, base);
}
REX_EXTERN(__imp__sub_829211E8);
REX_HOOK_RAW(sub_829211E8) {
  svr2011::d3d_trace::OnCall(356, ctx, base);
  __imp__sub_829211E8(ctx, base);
}
REX_EXTERN(__imp__sub_82921230);
REX_HOOK_RAW(sub_82921230) {
  svr2011::d3d_trace::OnCall(357, ctx, base);
  __imp__sub_82921230(ctx, base);
}
REX_EXTERN(__imp__sub_82921360);
REX_HOOK_RAW(sub_82921360) {
  svr2011::d3d_trace::OnCall(358, ctx, base);
  __imp__sub_82921360(ctx, base);
}
REX_EXTERN(__imp__sub_82921450);
REX_HOOK_RAW(sub_82921450) {
  svr2011::d3d_trace::OnCall(359, ctx, base);
  __imp__sub_82921450(ctx, base);
}
REX_EXTERN(__imp__sub_82921548);
REX_HOOK_RAW(sub_82921548) {
  svr2011::d3d_trace::OnCall(360, ctx, base);
  __imp__sub_82921548(ctx, base);
}
REX_EXTERN(__imp__sub_82921638);
REX_HOOK_RAW(sub_82921638) {
  svr2011::d3d_trace::OnCall(361, ctx, base);
  __imp__sub_82921638(ctx, base);
}
REX_EXTERN(__imp__sub_82921688);
REX_HOOK_RAW(sub_82921688) {
  svr2011::d3d_trace::OnCall(362, ctx, base);
  __imp__sub_82921688(ctx, base);
}
REX_EXTERN(__imp__sub_82921698);
REX_HOOK_RAW(sub_82921698) {
  svr2011::d3d_trace::OnCall(363, ctx, base);
  __imp__sub_82921698(ctx, base);
}
REX_EXTERN(__imp__sub_82921B58);
REX_HOOK_RAW(sub_82921B58) {
  svr2011::d3d_trace::OnCall(364, ctx, base);
  __imp__sub_82921B58(ctx, base);
}
REX_EXTERN(__imp__sub_82921FD0);
REX_HOOK_RAW(sub_82921FD0) {
  svr2011::d3d_trace::OnCall(365, ctx, base);
  __imp__sub_82921FD0(ctx, base);
}
REX_EXTERN(__imp__sub_82922068);
REX_HOOK_RAW(sub_82922068) {
  svr2011::d3d_trace::OnCall(366, ctx, base);
  __imp__sub_82922068(ctx, base);
}
REX_EXTERN(__imp__sub_82922118);
REX_HOOK_RAW(sub_82922118) {
  svr2011::d3d_trace::OnCall(367, ctx, base);
  __imp__sub_82922118(ctx, base);
}
REX_EXTERN(__imp__sub_82922230);
REX_HOOK_RAW(sub_82922230) {
  svr2011::d3d_trace::OnCall(368, ctx, base);
  __imp__sub_82922230(ctx, base);
}
REX_EXTERN(__imp__sub_82922298);
REX_HOOK_RAW(sub_82922298) {
  svr2011::d3d_trace::OnCall(369, ctx, base);
  __imp__sub_82922298(ctx, base);
}
REX_EXTERN(__imp__sub_829222F0);
REX_HOOK_RAW(sub_829222F0) {
  svr2011::d3d_trace::OnCall(370, ctx, base);
  __imp__sub_829222F0(ctx, base);
}
REX_EXTERN(__imp__sub_82922388);
REX_HOOK_RAW(sub_82922388) {
  svr2011::d3d_trace::OnCall(371, ctx, base);
  __imp__sub_82922388(ctx, base);
}
REX_EXTERN(__imp__sub_82922400);
REX_HOOK_RAW(sub_82922400) {
  svr2011::d3d_trace::OnCall(372, ctx, base);
  __imp__sub_82922400(ctx, base);
}
REX_EXTERN(__imp__sub_82922630);
REX_HOOK_RAW(sub_82922630) {
  svr2011::d3d_trace::OnCall(373, ctx, base);
  __imp__sub_82922630(ctx, base);
}
REX_EXTERN(__imp__sub_82922718);
REX_HOOK_RAW(sub_82922718) {
  svr2011::d3d_trace::OnCall(374, ctx, base);
  __imp__sub_82922718(ctx, base);
}
REX_EXTERN(__imp__sub_829227E8);
REX_HOOK_RAW(sub_829227E8) {
  svr2011::d3d_trace::OnCall(375, ctx, base);
  __imp__sub_829227E8(ctx, base);
}
REX_EXTERN(__imp__sub_82922848);
REX_HOOK_RAW(sub_82922848) {
  svr2011::d3d_trace::OnCall(376, ctx, base);
  __imp__sub_82922848(ctx, base);
}
REX_EXTERN(__imp__sub_829228A8);
REX_HOOK_RAW(sub_829228A8) {
  svr2011::d3d_trace::OnCall(377, ctx, base);
  __imp__sub_829228A8(ctx, base);
}
REX_EXTERN(__imp__sub_829228F0);
REX_HOOK_RAW(sub_829228F0) {
  svr2011::d3d_trace::OnCall(378, ctx, base);
  __imp__sub_829228F0(ctx, base);
}
REX_EXTERN(__imp__sub_82922A00);
REX_HOOK_RAW(sub_82922A00) {
  svr2011::d3d_trace::OnCall(379, ctx, base);
  __imp__sub_82922A00(ctx, base);
}
REX_EXTERN(__imp__sub_82922AA0);
REX_HOOK_RAW(sub_82922AA0) {
  svr2011::d3d_trace::OnCall(380, ctx, base);
  __imp__sub_82922AA0(ctx, base);
}
REX_EXTERN(__imp__sub_82922B20);
REX_HOOK_RAW(sub_82922B20) {
  svr2011::d3d_trace::OnCall(381, ctx, base);
  __imp__sub_82922B20(ctx, base);
}
REX_EXTERN(__imp__sub_82922C58);
REX_HOOK_RAW(sub_82922C58) {
  svr2011::d3d_trace::OnCall(382, ctx, base);
  __imp__sub_82922C58(ctx, base);
}
REX_EXTERN(__imp__sub_82923020);
REX_HOOK_RAW(sub_82923020) {
  svr2011::d3d_trace::OnCall(383, ctx, base);
  __imp__sub_82923020(ctx, base);
}
REX_EXTERN(__imp__sub_829231E0);
REX_HOOK_RAW(sub_829231E0) {
  svr2011::d3d_trace::OnCall(384, ctx, base);
  __imp__sub_829231E0(ctx, base);
}
REX_EXTERN(__imp__sub_82923320);
REX_HOOK_RAW(sub_82923320) {
  svr2011::d3d_trace::OnCall(385, ctx, base);
  __imp__sub_82923320(ctx, base);
}
REX_EXTERN(__imp__sub_829234D0);
REX_HOOK_RAW(sub_829234D0) {
  svr2011::d3d_trace::OnCall(386, ctx, base);
  __imp__sub_829234D0(ctx, base);
}
REX_EXTERN(__imp__sub_82923720);
REX_HOOK_RAW(sub_82923720) {
  svr2011::d3d_trace::OnCall(387, ctx, base);
  __imp__sub_82923720(ctx, base);
}
REX_EXTERN(__imp__sub_82923740);
REX_HOOK_RAW(sub_82923740) {
  svr2011::d3d_trace::OnCall(388, ctx, base);
  __imp__sub_82923740(ctx, base);
}
REX_EXTERN(__imp__sub_829238C8);
REX_HOOK_RAW(sub_829238C8) {
  svr2011::d3d_trace::OnCall(389, ctx, base);
  __imp__sub_829238C8(ctx, base);
}
REX_EXTERN(__imp__sub_829239D0);
REX_HOOK_RAW(sub_829239D0) {
  svr2011::d3d_trace::OnCall(390, ctx, base);
  __imp__sub_829239D0(ctx, base);
}
REX_EXTERN(__imp__sub_82923A08);
REX_HOOK_RAW(sub_82923A08) {
  svr2011::d3d_trace::OnCall(391, ctx, base);
  __imp__sub_82923A08(ctx, base);
}
REX_EXTERN(__imp__sub_82923A98);
REX_HOOK_RAW(sub_82923A98) {
  svr2011::d3d_trace::OnCall(392, ctx, base);
  __imp__sub_82923A98(ctx, base);
}
REX_EXTERN(__imp__sub_82923B00);
REX_HOOK_RAW(sub_82923B00) {
  svr2011::d3d_trace::OnCall(393, ctx, base);
  __imp__sub_82923B00(ctx, base);
}
REX_EXTERN(__imp__sub_82923B78);
REX_HOOK_RAW(sub_82923B78) {
  svr2011::d3d_trace::OnCall(394, ctx, base);
  __imp__sub_82923B78(ctx, base);
}
REX_EXTERN(__imp__sub_82923BF0);
REX_HOOK_RAW(sub_82923BF0) {
  svr2011::d3d_trace::OnCall(395, ctx, base);
  __imp__sub_82923BF0(ctx, base);
}
REX_EXTERN(__imp__sub_82923FB8);
REX_HOOK_RAW(sub_82923FB8) {
  svr2011::d3d_trace::OnCall(396, ctx, base);
  __imp__sub_82923FB8(ctx, base);
}
REX_EXTERN(__imp__sub_82924060);
REX_HOOK_RAW(sub_82924060) {
  svr2011::d3d_trace::OnCall(397, ctx, base);
  __imp__sub_82924060(ctx, base);
}
REX_EXTERN(__imp__sub_82924110);
REX_HOOK_RAW(sub_82924110) {
  svr2011::d3d_trace::OnCall(398, ctx, base);
  __imp__sub_82924110(ctx, base);
}
REX_EXTERN(__imp__sub_8292416C);
REX_HOOK_RAW(sub_8292416C) {
  svr2011::d3d_trace::OnCall(399, ctx, base);
  __imp__sub_8292416C(ctx, base);
}
REX_EXTERN(__imp__sub_82924170);
REX_HOOK_RAW(sub_82924170) {
  svr2011::d3d_trace::OnCall(400, ctx, base);
  __imp__sub_82924170(ctx, base);
}
REX_EXTERN(__imp__sub_82924220);
REX_HOOK_RAW(sub_82924220) {
  svr2011::d3d_trace::OnCall(401, ctx, base);
  __imp__sub_82924220(ctx, base);
}
REX_EXTERN(__imp__sub_829242D0);
REX_HOOK_RAW(sub_829242D0) {
  svr2011::d3d_trace::OnCall(402, ctx, base);
  __imp__sub_829242D0(ctx, base);
}
REX_EXTERN(__imp__sub_82924350);
REX_HOOK_RAW(sub_82924350) {
  svr2011::d3d_trace::OnCall(403, ctx, base);
  __imp__sub_82924350(ctx, base);
}
REX_EXTERN(__imp__sub_829243C8);
REX_HOOK_RAW(sub_829243C8) {
  svr2011::d3d_trace::OnCall(404, ctx, base);
  __imp__sub_829243C8(ctx, base);
}
REX_EXTERN(__imp__sub_82924420);
REX_HOOK_RAW(sub_82924420) {
  svr2011::d3d_trace::OnCall(405, ctx, base);
  __imp__sub_82924420(ctx, base);
}
REX_EXTERN(__imp__sub_829244F8);
REX_HOOK_RAW(sub_829244F8) {
  svr2011::d3d_trace::OnCall(406, ctx, base);
  __imp__sub_829244F8(ctx, base);
}
REX_EXTERN(__imp__sub_82924638);
REX_HOOK_RAW(sub_82924638) {
  svr2011::d3d_trace::OnCall(407, ctx, base);
  __imp__sub_82924638(ctx, base);
}
REX_EXTERN(__imp__sub_82924688);
REX_HOOK_RAW(sub_82924688) {
  svr2011::d3d_trace::OnCall(408, ctx, base);
  __imp__sub_82924688(ctx, base);
}
REX_EXTERN(__imp__sub_829247F8);
REX_HOOK_RAW(sub_829247F8) {
  svr2011::d3d_trace::OnCall(409, ctx, base);
  __imp__sub_829247F8(ctx, base);
}
REX_EXTERN(__imp__sub_829248B0);
REX_HOOK_RAW(sub_829248B0) {
  svr2011::d3d_trace::OnCall(410, ctx, base);
  __imp__sub_829248B0(ctx, base);
}
REX_EXTERN(__imp__sub_82924AA8);
REX_HOOK_RAW(sub_82924AA8) {
  svr2011::d3d_trace::OnCall(411, ctx, base);
  __imp__sub_82924AA8(ctx, base);
}
REX_EXTERN(__imp__sub_82924E40);
REX_HOOK_RAW(sub_82924E40) {
  svr2011::d3d_trace::OnCall(412, ctx, base);
  __imp__sub_82924E40(ctx, base);
}
REX_EXTERN(__imp__sub_82924F00);
REX_HOOK_RAW(sub_82924F00) {
  svr2011::d3d_trace::OnCall(413, ctx, base);
  __imp__sub_82924F00(ctx, base);
}
REX_EXTERN(__imp__sub_82925080);
REX_HOOK_RAW(sub_82925080) {
  svr2011::d3d_trace::OnCall(414, ctx, base);
  __imp__sub_82925080(ctx, base);
}
REX_EXTERN(__imp__sub_829251D8);
REX_HOOK_RAW(sub_829251D8) {
  svr2011::d3d_trace::OnCall(415, ctx, base);
  __imp__sub_829251D8(ctx, base);
}
REX_EXTERN(__imp__sub_82925328);
REX_HOOK_RAW(sub_82925328) {
  svr2011::d3d_trace::OnCall(416, ctx, base);
  __imp__sub_82925328(ctx, base);
}
REX_EXTERN(__imp__sub_82925950);
REX_HOOK_RAW(sub_82925950) {
  svr2011::d3d_trace::OnCall(417, ctx, base);
  __imp__sub_82925950(ctx, base);
}
REX_EXTERN(__imp__sub_82925A20);
REX_HOOK_RAW(sub_82925A20) {
  svr2011::d3d_trace::OnCall(418, ctx, base);
  __imp__sub_82925A20(ctx, base);
}
REX_EXTERN(__imp__sub_82925AD8);
REX_HOOK_RAW(sub_82925AD8) {
  svr2011::d3d_trace::OnCall(419, ctx, base);
  __imp__sub_82925AD8(ctx, base);
}
REX_EXTERN(__imp__sub_82925C28);
REX_HOOK_RAW(sub_82925C28) {
  svr2011::d3d_trace::OnCall(420, ctx, base);
  __imp__sub_82925C28(ctx, base);
}
REX_EXTERN(__imp__sub_82925D78);
REX_HOOK_RAW(sub_82925D78) {
  svr2011::d3d_trace::OnCall(421, ctx, base);
  __imp__sub_82925D78(ctx, base);
}
REX_EXTERN(__imp__sub_82925EC0);
REX_HOOK_RAW(sub_82925EC0) {
  svr2011::d3d_trace::OnCall(422, ctx, base);
  __imp__sub_82925EC0(ctx, base);
}
REX_EXTERN(__imp__sub_82926000);
REX_HOOK_RAW(sub_82926000) {
  svr2011::d3d_trace::OnCall(423, ctx, base);
  __imp__sub_82926000(ctx, base);
}
REX_EXTERN(__imp__sub_82926970);
REX_HOOK_RAW(sub_82926970) {
  svr2011::d3d_trace::OnCall(424, ctx, base);
  __imp__sub_82926970(ctx, base);
}
REX_EXTERN(__imp__sub_829269F0);
REX_HOOK_RAW(sub_829269F0) {
  svr2011::d3d_trace::OnCall(425, ctx, base);
  __imp__sub_829269F0(ctx, base);
}
REX_EXTERN(__imp__sub_82926AB8);
REX_HOOK_RAW(sub_82926AB8) {
  svr2011::d3d_trace::OnCall(426, ctx, base);
  __imp__sub_82926AB8(ctx, base);
}
REX_EXTERN(__imp__sub_82926AC8);
REX_HOOK_RAW(sub_82926AC8) {
  svr2011::d3d_trace::OnCall(427, ctx, base);
  __imp__sub_82926AC8(ctx, base);
}
REX_EXTERN(__imp__sub_82926AE0);
REX_HOOK_RAW(sub_82926AE0) {
  svr2011::d3d_trace::OnCall(428, ctx, base);
  __imp__sub_82926AE0(ctx, base);
}
REX_EXTERN(__imp__sub_82926B60);
REX_HOOK_RAW(sub_82926B60) {
  svr2011::d3d_trace::OnCall(429, ctx, base);
  __imp__sub_82926B60(ctx, base);
}
REX_EXTERN(__imp__sub_82926DC8);
REX_HOOK_RAW(sub_82926DC8) {
  svr2011::d3d_trace::OnCall(430, ctx, base);
  __imp__sub_82926DC8(ctx, base);
}
REX_EXTERN(__imp__sub_82926F10);
REX_HOOK_RAW(sub_82926F10) {
  svr2011::d3d_trace::OnCall(431, ctx, base);
  __imp__sub_82926F10(ctx, base);
}
REX_EXTERN(__imp__sub_82927300);
REX_HOOK_RAW(sub_82927300) {
  svr2011::d3d_trace::OnCall(432, ctx, base);
  __imp__sub_82927300(ctx, base);
}
REX_EXTERN(__imp__sub_829273C0);
REX_HOOK_RAW(sub_829273C0) {
  svr2011::d3d_trace::OnCall(433, ctx, base);
  __imp__sub_829273C0(ctx, base);
}
REX_EXTERN(__imp__sub_82927468);
REX_HOOK_RAW(sub_82927468) {
  svr2011::d3d_trace::OnCall(434, ctx, base);
  __imp__sub_82927468(ctx, base);
}
REX_EXTERN(__imp__sub_82927488);
REX_HOOK_RAW(sub_82927488) {
  svr2011::d3d_trace::OnCall(435, ctx, base);
  __imp__sub_82927488(ctx, base);
}
REX_EXTERN(__imp__sub_829274C8);
REX_HOOK_RAW(sub_829274C8) {
  svr2011::d3d_trace::OnCall(436, ctx, base);
  __imp__sub_829274C8(ctx, base);
}
REX_EXTERN(__imp__sub_829274F0);
REX_HOOK_RAW(sub_829274F0) {
  svr2011::d3d_trace::OnCall(437, ctx, base);
  __imp__sub_829274F0(ctx, base);
}
REX_EXTERN(__imp__sub_82927758);
REX_HOOK_RAW(sub_82927758) {
  svr2011::d3d_trace::OnCall(438, ctx, base);
  __imp__sub_82927758(ctx, base);
}
REX_EXTERN(__imp__sub_829279A8);
REX_HOOK_RAW(sub_829279A8) {
  svr2011::d3d_trace::OnCall(439, ctx, base);
  __imp__sub_829279A8(ctx, base);
}
REX_EXTERN(__imp__sub_82927A58);
REX_HOOK_RAW(sub_82927A58) {
  svr2011::d3d_trace::OnCall(440, ctx, base);
  __imp__sub_82927A58(ctx, base);
}
REX_EXTERN(__imp__sub_82927AB0);
REX_HOOK_RAW(sub_82927AB0) {
  svr2011::d3d_trace::OnCall(441, ctx, base);
  __imp__sub_82927AB0(ctx, base);
}
REX_EXTERN(__imp__sub_82927B58);
REX_HOOK_RAW(sub_82927B58) {
  svr2011::d3d_trace::OnCall(442, ctx, base);
  __imp__sub_82927B58(ctx, base);
}
REX_EXTERN(__imp__sub_82927BF0);
REX_HOOK_RAW(sub_82927BF0) {
  svr2011::d3d_trace::OnCall(443, ctx, base);
  __imp__sub_82927BF0(ctx, base);
}
REX_EXTERN(__imp__sub_82927C60);
REX_HOOK_RAW(sub_82927C60) {
  svr2011::d3d_trace::OnCall(444, ctx, base);
  __imp__sub_82927C60(ctx, base);
}
REX_EXTERN(__imp__sub_82927EC8);
REX_HOOK_RAW(sub_82927EC8) {
  svr2011::d3d_trace::OnCall(445, ctx, base);
  __imp__sub_82927EC8(ctx, base);
}
REX_EXTERN(__imp__sub_82927F18);
REX_HOOK_RAW(sub_82927F18) {
  svr2011::d3d_trace::OnCall(446, ctx, base);
  __imp__sub_82927F18(ctx, base);
}
REX_EXTERN(__imp__sub_82927F98);
REX_HOOK_RAW(sub_82927F98) {
  svr2011::d3d_trace::OnCall(447, ctx, base);
  __imp__sub_82927F98(ctx, base);
}
REX_EXTERN(__imp__sub_82928140);
REX_HOOK_RAW(sub_82928140) {
  svr2011::d3d_trace::OnCall(448, ctx, base);
  __imp__sub_82928140(ctx, base);
}
REX_EXTERN(__imp__sub_82928190);
REX_HOOK_RAW(sub_82928190) {
  svr2011::d3d_trace::OnCall(449, ctx, base);
  __imp__sub_82928190(ctx, base);
}
REX_EXTERN(__imp__sub_82928240);
REX_HOOK_RAW(sub_82928240) {
  svr2011::d3d_trace::OnCall(450, ctx, base);
  __imp__sub_82928240(ctx, base);
}
REX_EXTERN(__imp__sub_829282F0);
REX_HOOK_RAW(sub_829282F0) {
  svr2011::d3d_trace::OnCall(451, ctx, base);
  __imp__sub_829282F0(ctx, base);
}
REX_EXTERN(__imp__sub_82928470);
REX_HOOK_RAW(sub_82928470) {
  svr2011::d3d_trace::OnCall(452, ctx, base);
  __imp__sub_82928470(ctx, base);
}
REX_EXTERN(__imp__sub_82928508);
REX_HOOK_RAW(sub_82928508) {
  svr2011::d3d_trace::OnCall(453, ctx, base);
  __imp__sub_82928508(ctx, base);
}
REX_EXTERN(__imp__sub_82928590);
REX_HOOK_RAW(sub_82928590) {
  svr2011::d3d_trace::OnCall(454, ctx, base);
  __imp__sub_82928590(ctx, base);
}
REX_EXTERN(__imp__sub_82928688);
REX_HOOK_RAW(sub_82928688) {
  svr2011::d3d_trace::OnCall(455, ctx, base);
  __imp__sub_82928688(ctx, base);
}
REX_EXTERN(__imp__sub_82928778);
REX_HOOK_RAW(sub_82928778) {
  svr2011::d3d_trace::OnCall(456, ctx, base);
  __imp__sub_82928778(ctx, base);
}
REX_EXTERN(__imp__sub_829287BC);
REX_HOOK_RAW(sub_829287BC) {
  svr2011::d3d_trace::OnCall(457, ctx, base);
  __imp__sub_829287BC(ctx, base);
}
REX_EXTERN(__imp__sub_829287C0);
REX_HOOK_RAW(sub_829287C0) {
  svr2011::d3d_trace::OnCall(458, ctx, base);
  __imp__sub_829287C0(ctx, base);
}
REX_EXTERN(__imp__sub_82928820);
REX_HOOK_RAW(sub_82928820) {
  svr2011::d3d_trace::OnCall(459, ctx, base);
  __imp__sub_82928820(ctx, base);
}
REX_EXTERN(__imp__sub_82928828);
REX_HOOK_RAW(sub_82928828) {
  svr2011::d3d_trace::OnCall(460, ctx, base);
  __imp__sub_82928828(ctx, base);
}
REX_EXTERN(__imp__sub_82928998);
REX_HOOK_RAW(sub_82928998) {
  svr2011::d3d_trace::OnCall(461, ctx, base);
  __imp__sub_82928998(ctx, base);
}
REX_EXTERN(__imp__sub_82928A00);
REX_HOOK_RAW(sub_82928A00) {
  svr2011::d3d_trace::OnCall(462, ctx, base);
  __imp__sub_82928A00(ctx, base);
}
REX_EXTERN(__imp__sub_82928A58);
REX_HOOK_RAW(sub_82928A58) {
  svr2011::d3d_trace::OnCall(463, ctx, base);
  __imp__sub_82928A58(ctx, base);
}
REX_EXTERN(__imp__sub_82928AE0);
REX_HOOK_RAW(sub_82928AE0) {
  svr2011::d3d_trace::OnCall(464, ctx, base);
  __imp__sub_82928AE0(ctx, base);
}
REX_EXTERN(__imp__sub_82928B40);
REX_HOOK_RAW(sub_82928B40) {
  svr2011::d3d_trace::OnCall(465, ctx, base);
  __imp__sub_82928B40(ctx, base);
}
REX_EXTERN(__imp__sub_82928C60);
REX_HOOK_RAW(sub_82928C60) {
  svr2011::d3d_trace::OnCall(466, ctx, base);
  __imp__sub_82928C60(ctx, base);
}
REX_EXTERN(__imp__sub_82928C70);
REX_HOOK_RAW(sub_82928C70) {
  svr2011::d3d_trace::OnCall(467, ctx, base);
  __imp__sub_82928C70(ctx, base);
}
REX_EXTERN(__imp__sub_82928CE0);
REX_HOOK_RAW(sub_82928CE0) {
  svr2011::d3d_trace::OnCall(468, ctx, base);
  __imp__sub_82928CE0(ctx, base);
}
REX_EXTERN(__imp__sub_82928D48);
REX_HOOK_RAW(sub_82928D48) {
  svr2011::d3d_trace::OnCall(469, ctx, base);
  __imp__sub_82928D48(ctx, base);
}
REX_EXTERN(__imp__sub_82928DE8);
REX_HOOK_RAW(sub_82928DE8) {
  svr2011::d3d_trace::OnCall(470, ctx, base);
  __imp__sub_82928DE8(ctx, base);
}
REX_EXTERN(__imp__sub_82928E80);
REX_HOOK_RAW(sub_82928E80) {
  svr2011::d3d_trace::OnCall(471, ctx, base);
  __imp__sub_82928E80(ctx, base);
}
REX_EXTERN(__imp__sub_82928ED8);
REX_HOOK_RAW(sub_82928ED8) {
  svr2011::d3d_trace::OnCall(472, ctx, base);
  __imp__sub_82928ED8(ctx, base);
}
REX_EXTERN(__imp__sub_82928F50);
REX_HOOK_RAW(sub_82928F50) {
  svr2011::d3d_trace::OnCall(473, ctx, base);
  __imp__sub_82928F50(ctx, base);
}
REX_EXTERN(__imp__sub_82929028);
REX_HOOK_RAW(sub_82929028) {
  svr2011::d3d_trace::OnCall(474, ctx, base);
  __imp__sub_82929028(ctx, base);
}
REX_EXTERN(__imp__sub_829290F0);
REX_HOOK_RAW(sub_829290F0) {
  svr2011::d3d_trace::OnCall(475, ctx, base);
  __imp__sub_829290F0(ctx, base);
}
REX_EXTERN(__imp__sub_82929158);
REX_HOOK_RAW(sub_82929158) {
  svr2011::d3d_trace::OnCall(476, ctx, base);
  __imp__sub_82929158(ctx, base);
}
REX_EXTERN(__imp__sub_829291B0);
REX_HOOK_RAW(sub_829291B0) {
  svr2011::d3d_trace::OnCall(477, ctx, base);
  __imp__sub_829291B0(ctx, base);
}
REX_EXTERN(__imp__sub_829291F8);
REX_HOOK_RAW(sub_829291F8) {
  svr2011::d3d_trace::OnCall(478, ctx, base);
  __imp__sub_829291F8(ctx, base);
}
REX_EXTERN(__imp__sub_82929350);
REX_HOOK_RAW(sub_82929350) {
  svr2011::d3d_trace::OnCall(479, ctx, base);
  __imp__sub_82929350(ctx, base);
}
REX_EXTERN(__imp__sub_829293F0);
REX_HOOK_RAW(sub_829293F0) {
  svr2011::d3d_trace::OnCall(480, ctx, base);
  __imp__sub_829293F0(ctx, base);
}
REX_EXTERN(__imp__sub_82929500);
REX_HOOK_RAW(sub_82929500) {
  svr2011::d3d_trace::OnCall(481, ctx, base);
  __imp__sub_82929500(ctx, base);
}
REX_EXTERN(__imp__sub_82929950);
REX_HOOK_RAW(sub_82929950) {
  svr2011::d3d_trace::OnCall(482, ctx, base);
  __imp__sub_82929950(ctx, base);
}
REX_EXTERN(__imp__sub_82929E30);
REX_HOOK_RAW(sub_82929E30) {
  svr2011::d3d_trace::OnCall(483, ctx, base);
  __imp__sub_82929E30(ctx, base);
}
REX_EXTERN(__imp__sub_82929E38);
REX_HOOK_RAW(sub_82929E38) {
  svr2011::d3d_trace::OnCall(484, ctx, base);
  __imp__sub_82929E38(ctx, base);
}
REX_EXTERN(__imp__sub_8292A018);
REX_HOOK_RAW(sub_8292A018) {
  svr2011::d3d_trace::OnCall(485, ctx, base);
  __imp__sub_8292A018(ctx, base);
}
REX_EXTERN(__imp__sub_8292A118);
REX_HOOK_RAW(sub_8292A118) {
  svr2011::d3d_trace::OnCall(486, ctx, base);
  __imp__sub_8292A118(ctx, base);
}
REX_EXTERN(__imp__sub_8292A1D0);
REX_HOOK_RAW(sub_8292A1D0) {
  svr2011::d3d_trace::OnCall(487, ctx, base);
  __imp__sub_8292A1D0(ctx, base);
}
REX_EXTERN(__imp__sub_8292A270);
REX_HOOK_RAW(sub_8292A270) {
  svr2011::d3d_trace::OnCall(488, ctx, base);
  __imp__sub_8292A270(ctx, base);
}
REX_EXTERN(__imp__sub_8292AA28);
REX_HOOK_RAW(sub_8292AA28) {
  svr2011::d3d_trace::OnCall(489, ctx, base);
  __imp__sub_8292AA28(ctx, base);
}
REX_EXTERN(__imp__sub_8292AEC0);
REX_HOOK_RAW(sub_8292AEC0) {
  svr2011::d3d_trace::OnCall(490, ctx, base);
  __imp__sub_8292AEC0(ctx, base);
}
REX_EXTERN(__imp__sub_8292B208);
REX_HOOK_RAW(sub_8292B208) {
  svr2011::d3d_trace::OnCall(491, ctx, base);
  __imp__sub_8292B208(ctx, base);
}
REX_EXTERN(__imp__sub_8292B920);
REX_HOOK_RAW(sub_8292B920) {
  svr2011::d3d_trace::OnCall(492, ctx, base);
  __imp__sub_8292B920(ctx, base);
}
REX_EXTERN(__imp__sub_8292BA50);
REX_HOOK_RAW(sub_8292BA50) {
  svr2011::d3d_trace::OnCall(493, ctx, base);
  __imp__sub_8292BA50(ctx, base);
}
REX_EXTERN(__imp__sub_8292BBC8);
REX_HOOK_RAW(sub_8292BBC8) {
  svr2011::d3d_trace::OnCall(494, ctx, base);
  __imp__sub_8292BBC8(ctx, base);
}
REX_EXTERN(__imp__sub_8292BC58);
REX_HOOK_RAW(sub_8292BC58) {
  svr2011::d3d_trace::OnCall(495, ctx, base);
  __imp__sub_8292BC58(ctx, base);
}
REX_EXTERN(__imp__sub_8292BD30);
REX_HOOK_RAW(sub_8292BD30) {
  svr2011::d3d_trace::OnCall(496, ctx, base);
  __imp__sub_8292BD30(ctx, base);
}
REX_EXTERN(__imp__sub_8292BFD0);
REX_HOOK_RAW(sub_8292BFD0) {
  svr2011::d3d_trace::OnCall(497, ctx, base);
  __imp__sub_8292BFD0(ctx, base);
}
REX_EXTERN(__imp__sub_8292C0F8);
REX_HOOK_RAW(sub_8292C0F8) {
  svr2011::d3d_trace::OnCall(498, ctx, base);
  __imp__sub_8292C0F8(ctx, base);
}
REX_EXTERN(__imp__sub_8292C170);
REX_HOOK_RAW(sub_8292C170) {
  svr2011::d3d_trace::OnCall(499, ctx, base);
  __imp__sub_8292C170(ctx, base);
}
REX_EXTERN(__imp__sub_8292C1D0);
REX_HOOK_RAW(sub_8292C1D0) {
  svr2011::d3d_trace::OnCall(500, ctx, base);
  __imp__sub_8292C1D0(ctx, base);
}
REX_EXTERN(__imp__sub_8292C270);
REX_HOOK_RAW(sub_8292C270) {
  svr2011::d3d_trace::OnCall(501, ctx, base);
  __imp__sub_8292C270(ctx, base);
}
REX_EXTERN(__imp__sub_8292C358);
REX_HOOK_RAW(sub_8292C358) {
  svr2011::d3d_trace::OnCall(502, ctx, base);
  __imp__sub_8292C358(ctx, base);
}
REX_EXTERN(__imp__sub_8292C540);
REX_HOOK_RAW(sub_8292C540) {
  svr2011::d3d_trace::OnCall(503, ctx, base);
  __imp__sub_8292C540(ctx, base);
}
REX_EXTERN(__imp__sub_8292C998);
REX_HOOK_RAW(sub_8292C998) {
  svr2011::d3d_trace::OnCall(504, ctx, base);
  __imp__sub_8292C998(ctx, base);
}
REX_EXTERN(__imp__sub_8292CB40);
REX_HOOK_RAW(sub_8292CB40) {
  svr2011::d3d_trace::OnCall(505, ctx, base);
  __imp__sub_8292CB40(ctx, base);
}
REX_EXTERN(__imp__sub_8292CC00);
REX_HOOK_RAW(sub_8292CC00) {
  svr2011::d3d_trace::OnCall(506, ctx, base);
  __imp__sub_8292CC00(ctx, base);
}
REX_EXTERN(__imp__sub_8292CC58);
REX_HOOK_RAW(sub_8292CC58) {
  svr2011::d3d_trace::OnCall(507, ctx, base);
  __imp__sub_8292CC58(ctx, base);
}
REX_EXTERN(__imp__sub_8292CD60);
REX_HOOK_RAW(sub_8292CD60) {
  svr2011::d3d_trace::OnCall(508, ctx, base);
  __imp__sub_8292CD60(ctx, base);
}
REX_EXTERN(__imp__sub_8292CE68);
REX_HOOK_RAW(sub_8292CE68) {
  svr2011::d3d_trace::OnCall(509, ctx, base);
  __imp__sub_8292CE68(ctx, base);
}
REX_EXTERN(__imp__sub_8292D2A0);
REX_HOOK_RAW(sub_8292D2A0) {
  svr2011::d3d_trace::OnCall(510, ctx, base);
  __imp__sub_8292D2A0(ctx, base);
}
REX_EXTERN(__imp__sub_8292D580);
REX_HOOK_RAW(sub_8292D580) {
  svr2011::d3d_trace::OnCall(511, ctx, base);
  __imp__sub_8292D580(ctx, base);
}
REX_EXTERN(__imp__sub_8292DAA8);
REX_HOOK_RAW(sub_8292DAA8) {
  svr2011::d3d_trace::OnCall(512, ctx, base);
  __imp__sub_8292DAA8(ctx, base);
}
REX_EXTERN(__imp__sub_8292DC58);
REX_HOOK_RAW(sub_8292DC58) {
  svr2011::d3d_trace::OnCall(513, ctx, base);
  __imp__sub_8292DC58(ctx, base);
}
REX_EXTERN(__imp__sub_8292DCD8);
REX_HOOK_RAW(sub_8292DCD8) {
  svr2011::d3d_trace::OnCall(514, ctx, base);
  __imp__sub_8292DCD8(ctx, base);
}
REX_EXTERN(__imp__sub_8292DD08);
REX_HOOK_RAW(sub_8292DD08) {
  svr2011::d3d_trace::OnCall(515, ctx, base);
  __imp__sub_8292DD08(ctx, base);
}
REX_EXTERN(__imp__sub_8292DD20);
REX_HOOK_RAW(sub_8292DD20) {
  svr2011::d3d_trace::OnCall(516, ctx, base);
  __imp__sub_8292DD20(ctx, base);
}
REX_EXTERN(__imp__sub_8292DE08);
REX_HOOK_RAW(sub_8292DE08) {
  svr2011::d3d_trace::OnCall(517, ctx, base);
  __imp__sub_8292DE08(ctx, base);
}
REX_EXTERN(__imp__sub_8292DE20);
REX_HOOK_RAW(sub_8292DE20) {
  svr2011::d3d_trace::OnCall(518, ctx, base);
  __imp__sub_8292DE20(ctx, base);
}
REX_EXTERN(__imp__sub_8292DE38);
REX_HOOK_RAW(sub_8292DE38) {
  svr2011::d3d_trace::OnCall(519, ctx, base);
  __imp__sub_8292DE38(ctx, base);
}
REX_EXTERN(__imp__sub_8292DE70);
REX_HOOK_RAW(sub_8292DE70) {
  svr2011::d3d_trace::OnCall(520, ctx, base);
  __imp__sub_8292DE70(ctx, base);
}
REX_EXTERN(__imp__sub_8292DEC8);
REX_HOOK_RAW(sub_8292DEC8) {
  svr2011::d3d_trace::OnCall(521, ctx, base);
  __imp__sub_8292DEC8(ctx, base);
}
REX_EXTERN(__imp__sub_8292DF10);
REX_HOOK_RAW(sub_8292DF10) {
  svr2011::d3d_trace::OnCall(522, ctx, base);
  __imp__sub_8292DF10(ctx, base);
}
REX_EXTERN(__imp__sub_8292DF28);
REX_HOOK_RAW(sub_8292DF28) {
  svr2011::d3d_trace::OnCall(523, ctx, base);
  __imp__sub_8292DF28(ctx, base);
}
REX_EXTERN(__imp__sub_8292DF40);
REX_HOOK_RAW(sub_8292DF40) {
  svr2011::d3d_trace::OnCall(524, ctx, base);
  __imp__sub_8292DF40(ctx, base);
}
REX_EXTERN(__imp__sub_8292DF68);
REX_HOOK_RAW(sub_8292DF68) {
  svr2011::d3d_trace::OnCall(525, ctx, base);
  __imp__sub_8292DF68(ctx, base);
}
REX_EXTERN(__imp__sub_8292E220);
REX_HOOK_RAW(sub_8292E220) {
  svr2011::d3d_trace::OnCall(526, ctx, base);
  __imp__sub_8292E220(ctx, base);
}
REX_EXTERN(__imp__sub_8292E2A0);
REX_HOOK_RAW(sub_8292E2A0) {
  svr2011::d3d_trace::OnCall(527, ctx, base);
  __imp__sub_8292E2A0(ctx, base);
}
REX_EXTERN(__imp__sub_8292E3A8);
REX_HOOK_RAW(sub_8292E3A8) {
  svr2011::d3d_trace::OnCall(528, ctx, base);
  __imp__sub_8292E3A8(ctx, base);
}
REX_EXTERN(__imp__sub_8292EAC8);
REX_HOOK_RAW(sub_8292EAC8) {
  svr2011::d3d_trace::OnCall(529, ctx, base);
  __imp__sub_8292EAC8(ctx, base);
}
REX_EXTERN(__imp__sub_8292EB80);
REX_HOOK_RAW(sub_8292EB80) {
  svr2011::d3d_trace::OnCall(530, ctx, base);
  __imp__sub_8292EB80(ctx, base);
}
REX_EXTERN(__imp__sub_8292EFA0);
REX_HOOK_RAW(sub_8292EFA0) {
  svr2011::d3d_trace::OnCall(531, ctx, base);
  __imp__sub_8292EFA0(ctx, base);
}
REX_EXTERN(__imp__sub_8292EFD0);
REX_HOOK_RAW(sub_8292EFD0) {
  svr2011::d3d_trace::OnCall(532, ctx, base);
  __imp__sub_8292EFD0(ctx, base);
}
REX_EXTERN(__imp__sub_8292F338);
REX_HOOK_RAW(sub_8292F338) {
  svr2011::d3d_trace::OnCall(533, ctx, base);
  __imp__sub_8292F338(ctx, base);
}
REX_EXTERN(__imp__sub_8292FBF8);
REX_HOOK_RAW(sub_8292FBF8) {
  svr2011::d3d_trace::OnCall(534, ctx, base);
  __imp__sub_8292FBF8(ctx, base);
}
REX_EXTERN(__imp__sub_8292FCE8);
REX_HOOK_RAW(sub_8292FCE8) {
  svr2011::d3d_trace::OnCall(535, ctx, base);
  __imp__sub_8292FCE8(ctx, base);
}
REX_EXTERN(__imp__sub_8292FD00);
REX_HOOK_RAW(sub_8292FD00) {
  svr2011::d3d_trace::OnCall(536, ctx, base);
  __imp__sub_8292FD00(ctx, base);
}
REX_EXTERN(__imp__sub_8292FD70);
REX_HOOK_RAW(sub_8292FD70) {
  svr2011::d3d_trace::OnCall(537, ctx, base);
  __imp__sub_8292FD70(ctx, base);
}
REX_EXTERN(__imp__sub_8292FE58);
REX_HOOK_RAW(sub_8292FE58) {
  svr2011::d3d_trace::OnCall(538, ctx, base);
  __imp__sub_8292FE58(ctx, base);
}
REX_EXTERN(__imp__sub_8292FEF8);
REX_HOOK_RAW(sub_8292FEF8) {
  svr2011::d3d_trace::OnCall(539, ctx, base);
  __imp__sub_8292FEF8(ctx, base);
}
REX_EXTERN(__imp__sub_82930500);
REX_HOOK_RAW(sub_82930500) {
  svr2011::d3d_trace::OnCall(540, ctx, base);
  __imp__sub_82930500(ctx, base);
}
REX_EXTERN(__imp__sub_82930518);
REX_HOOK_RAW(sub_82930518) {
  svr2011::d3d_trace::OnCall(541, ctx, base);
  __imp__sub_82930518(ctx, base);
}
REX_EXTERN(__imp__sub_82931B88);
REX_HOOK_RAW(sub_82931B88) {
  svr2011::d3d_trace::OnCall(542, ctx, base);
  __imp__sub_82931B88(ctx, base);
}
REX_EXTERN(__imp__sub_82931BF8);
REX_HOOK_RAW(sub_82931BF8) {
  svr2011::d3d_trace::OnCall(543, ctx, base);
  __imp__sub_82931BF8(ctx, base);
}
REX_EXTERN(__imp__sub_82931CB0);
REX_HOOK_RAW(sub_82931CB0) {
  svr2011::d3d_trace::OnCall(544, ctx, base);
  __imp__sub_82931CB0(ctx, base);
}
REX_EXTERN(__imp__sub_82931D18);
REX_HOOK_RAW(sub_82931D18) {
  svr2011::d3d_trace::OnCall(545, ctx, base);
  __imp__sub_82931D18(ctx, base);
}
REX_EXTERN(__imp__sub_82931DA0);
REX_HOOK_RAW(sub_82931DA0) {
  svr2011::d3d_trace::OnCall(546, ctx, base);
  __imp__sub_82931DA0(ctx, base);
}
REX_EXTERN(__imp__sub_82931E40);
REX_HOOK_RAW(sub_82931E40) {
  svr2011::d3d_trace::OnCall(547, ctx, base);
  __imp__sub_82931E40(ctx, base);
}
REX_EXTERN(__imp__sub_82931F48);
REX_HOOK_RAW(sub_82931F48) {
  svr2011::d3d_trace::OnCall(548, ctx, base);
  __imp__sub_82931F48(ctx, base);
}
REX_EXTERN(__imp__sub_82931FB0);
REX_HOOK_RAW(sub_82931FB0) {
  svr2011::d3d_trace::OnCall(549, ctx, base);
  __imp__sub_82931FB0(ctx, base);
}
REX_EXTERN(__imp__sub_829320E8);
REX_HOOK_RAW(sub_829320E8) {
  svr2011::d3d_trace::OnCall(550, ctx, base);
  __imp__sub_829320E8(ctx, base);
}
REX_EXTERN(__imp__sub_82932120);
REX_HOOK_RAW(sub_82932120) {
  svr2011::d3d_trace::OnCall(551, ctx, base);
  __imp__sub_82932120(ctx, base);
}
REX_EXTERN(__imp__sub_829321B8);
REX_HOOK_RAW(sub_829321B8) {
  svr2011::d3d_trace::OnCall(552, ctx, base);
  __imp__sub_829321B8(ctx, base);
}
REX_EXTERN(__imp__sub_82932360);
REX_HOOK_RAW(sub_82932360) {
  svr2011::d3d_trace::OnCall(553, ctx, base);
  __imp__sub_82932360(ctx, base);
}
REX_EXTERN(__imp__sub_82932440);
REX_HOOK_RAW(sub_82932440) {
  svr2011::d3d_trace::OnCall(554, ctx, base);
  __imp__sub_82932440(ctx, base);
}
REX_EXTERN(__imp__sub_82932580);
REX_HOOK_RAW(sub_82932580) {
  svr2011::d3d_trace::OnCall(555, ctx, base);
  __imp__sub_82932580(ctx, base);
}
REX_EXTERN(__imp__sub_82932678);
REX_HOOK_RAW(sub_82932678) {
  svr2011::d3d_trace::OnCall(556, ctx, base);
  __imp__sub_82932678(ctx, base);
}
REX_EXTERN(__imp__sub_829329C0);
REX_HOOK_RAW(sub_829329C0) {
  svr2011::d3d_trace::OnCall(557, ctx, base);
  __imp__sub_829329C0(ctx, base);
}
REX_EXTERN(__imp__sub_82932C80);
REX_HOOK_RAW(sub_82932C80) {
  svr2011::d3d_trace::OnCall(558, ctx, base);
  __imp__sub_82932C80(ctx, base);
}
REX_EXTERN(__imp__sub_82932E18);
REX_HOOK_RAW(sub_82932E18) {
  svr2011::d3d_trace::OnCall(559, ctx, base);
  __imp__sub_82932E18(ctx, base);
}
REX_EXTERN(__imp__sub_82932ED0);
REX_HOOK_RAW(sub_82932ED0) {
  svr2011::d3d_trace::OnCall(560, ctx, base);
  __imp__sub_82932ED0(ctx, base);
}
REX_EXTERN(__imp__sub_82933070);
REX_HOOK_RAW(sub_82933070) {
  svr2011::d3d_trace::OnCall(561, ctx, base);
  __imp__sub_82933070(ctx, base);
}
