"""Generate src/d3d_trace_hooks.cpp: a counting hook on every function of the
game's statically linked D3D library (address range below), for the
SVR2011_D3D_TRACE build option. See src/d3d_trace.cpp for the reporting.

    python gen_d3d_trace.py [callgraph.json] [out.cpp]
"""
import json
import sys

D3D_LO, D3D_HI = 0x82914800, 0x82933240
# Already hooked elsewhere (frame_stats.cpp: Present); counted by frames.
SKIP = {0x8291AED0}


def main():
    graph = sys.argv[1] if len(sys.argv) > 1 else "runs/callgraph.json"
    out = sys.argv[2] if len(sys.argv) > 2 else "src/d3d_trace_hooks.cpp"
    g = json.load(open(graph))
    funcs = sorted((int(n[4:], 16), n) for n in g
                   if n.startswith("sub_") and D3D_LO <= int(n[4:], 16) < D3D_HI
                   and int(n[4:], 16) not in SKIP)
    lines = [
        "// Generated by tools/gen_d3d_trace.py - do not edit.",
        "// Counting hooks on the game's D3D library (SVR2011_D3D_TRACE builds).",
        "",
        '#include "d3d_trace.h"',
        "",
        "#include <rex/hook.h>",
        "#include <rex/ppc.h>",
        "",
        "namespace svr2011::d3d_trace {",
        f"const uint32_t kFunctionCount = {len(funcs)};",
        "const uint32_t kFunctions[] = {",
    ]
    lines += [f"    0x{a:08X}," for a, _ in funcs]
    lines += ["};", "}  // namespace svr2011::d3d_trace", ""]
    for i, (a, n) in enumerate(funcs):
        lines += [
            f"REX_EXTERN(__imp__{n});",
            f"REX_HOOK_RAW({n}) {{",
            f"  svr2011::d3d_trace::OnCall({i}, ctx, base);",
            f"  __imp__{n}(ctx, base);",
            "}",
        ]
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"{len(funcs)} hooks -> {out}")


if __name__ == "__main__":
    main()
