"""Makes src/native/managers_icon.inc, the character select's "M" pictures
(the managers: src/managers.cpp), from art/managers_tile.png (the grid tile)
and art/managers_banner.png (the wide picture beside the name).

The "?" tile's pictures are DXT5 textures packed in the game's menu files
(64 x 64 tile, 128 x 64 banner); the native renderer swaps them for these when
it uploads them (src/native/textures.cpp). The banner gets the soft-edged
frame the game's banners have (its alpha). Needs Pillow 11.2+
(pip install pillow):

    python tools/make_managers_icon.py
"""
import io
import math
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
PORT = os.path.dirname(HERE)
ART = os.path.join(PORT, "art")
OUT = os.path.join(PORT, "src", "native", "managers_icon.inc")


def dxt5(im: Image.Image) -> bytes:
    buf = io.BytesIO()
    im.save(buf, "DDS", pixel_format="DXT5")
    dds = buf.getvalue()
    assert dds[:4] == b"DDS " and dds[84:88] == b"DXT5", "Pillow did not write a DXT5 DDS"
    size = im.width * im.height  # (1 byte a pixel)
    data = dds[128:128 + size]
    assert len(data) == size
    return data


def frame_alpha(w: int, h: int) -> Image.Image:
    """The banners' frame: opaque inside, fading out over the outer ~7 pixels."""
    def edge(d):
        return 0.5 * (1 + math.erf((d - 7) / (math.sqrt(2) * 3)))
    a = Image.new("L", (w, h))
    a.putdata([round(255 * edge(min(x, w - 1 - x)) * edge(min(y, h - 1 - y)))
               for y in range(h) for x in range(w)])
    return a


def array(name: str, data: bytes, what: str) -> list:
    lines = [f"// {what}", f"const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return lines


def main() -> int:
    tile = Image.open(os.path.join(ART, "managers_tile.png")).convert("RGBA").resize((64, 64), Image.LANCZOS)
    banner = Image.open(os.path.join(ART, "managers_banner.png")).convert("RGB").resize((128, 64), Image.LANCZOS)
    banner = banner.convert("RGBA")
    banner.putalpha(frame_alpha(128, 64))
    lines = ["// Generated by tools/make_managers_icon.py from art/managers_*.png - do not edit.",
             "// DXT5, rows of 4 x 4 blocks top to bottom."]
    lines += array("kManagersTile", dxt5(tile), "64 x 64: the grid tile")
    lines += array("kManagersBanner", dxt5(banner), "128 x 64: the picture beside the name")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
