"""The character select's "MODDED" badge (superstar mods), in the style of the
game's "DOWNLOADABLE CONTENT" one (menuHD.pac MENU/CHSI 7001 DLCtex01.dds:
256 x 64 DXT5, white bold condensed text, dark outline, tilted).

    python make_modded_badge.py [--text MODDED] [--preview out.png]

Writes src/modded_badge.inc: the RGBA pixels (256 x 64) as a C array; the
game side (superstar_mods.cpp) encodes them to DXT5 at the size it finds.
"""
import argparse
import os

from PIL import Image, ImageDraw, ImageFont

W, H = 256, 64
FONT = r'C:\Windows\Fonts\arialbd.ttf'


def render(text):
    s = 4  # supersample
    big = Image.new('RGBA', (W * s, H * s), (0, 0, 0, 0))
    font = ImageFont.truetype(FONT, 46 * s)
    d = ImageDraw.Draw(big)
    box = d.textbbox((0, 0), text, font=font, stroke_width=3 * s)
    tw, th = box[2] - box[0], box[3] - box[1]
    txt = Image.new('RGBA', (tw + 8 * s, th + 8 * s), (0, 0, 0, 0))
    ImageDraw.Draw(txt).text((4 * s - box[0], 4 * s - box[1]), text, font=font, fill=(255, 255, 255, 255),
                             stroke_width=3 * s, stroke_fill=(10, 10, 10, 255))
    # condensed like the original (narrow letters), then fit and tilt
    txt = txt.resize((int(txt.width * 0.78), txt.height), Image.LANCZOS)
    scale = min((W * s * 0.80) / txt.width, (H * s * 0.62) / txt.height)
    txt = txt.resize((int(txt.width * scale), int(txt.height * scale)), Image.LANCZOS)
    txt = txt.rotate(7, resample=Image.BICUBIC, expand=True)
    big.alpha_composite(txt, ((W * s - txt.width) // 2, (H * s - txt.height) // 2))
    return big.resize((W, H), Image.LANCZOS)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--text', default='MODDED')
    ap.add_argument('--preview')
    a = ap.parse_args()
    img = render(a.text)
    if a.preview:
        bg = Image.new('RGBA', img.size, (40, 40, 90, 255))
        bg.alpha_composite(img)
        bg.resize((W * 2, H * 2)).save(a.preview)
    px = img.tobytes()
    out = os.path.join(os.path.dirname(__file__), '..', 'src', 'modded_badge.inc')
    with open(out, 'w', newline='\n') as f:
        f.write('// Generated by tools/make_modded_badge.py: "%s", %d x %d RGBA.\n' % (a.text, W, H))
        for i in range(0, len(px), 32):
            f.write(''.join('%d,' % b for b in px[i:i + 32]) + '\n')
    print('wrote', os.path.normpath(out))


if __name__ == '__main__':
    main()
